### ISSUE TITLE
Errors on node, sync broken after update to version 24

### ISSUE THREAD

**Issue by astudnev** [hashgraph/hedera-mirror-node#1325]
I had running mirror node on version 0.16.0-SNAPSHOT

It stuck today

I upgraded it to hedera-mirror-importer-0.24.0-rc1-exec

After the upgrade, migration it started and do not sync.

I see errors in log:

```console
Dec 05 14:03:57 node1-1 java[24252]: 2020-12-05T08:03:57.379-0600 ERROR scheduling-4 c.h.m.i.p.r.RecordFilePoller Error parsing file 2020-12-03T21_13_36.051261Z.rcd com.hedera.mirror.importer.exception.MissingFileException: File not found in the database: 2020-12-03T21_13_36.051261Z.rcd\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.lambda$onStart$0(SqlEntityListener.java:152)\\n        at java.base/java.util.Optional.orElseThrow(Optional.java:408)\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onStart(SqlEntityListener.java:152)\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onStart(SqlEntityListener.java:69)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:147)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser$$FastClassBySpringCGLIB$$8b9310db.invoke(<generated>)\\n        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)\\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\\n        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)\\n        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)\\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\\n        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser$$EnhancerBySpringCGLIB$$64e13bee.parse(<generated>)\\n        at com.hedera.mirror.importer.parser.record.RecordFilePoller.loadRecordFiles(RecordFilePoller.java:95)\\n        at com.hedera.mirror.importer.parser.record.RecordFilePoller.poll(RecordFilePoller.java:70)\\n        at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)\\n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n        at java.base/java.lang.reflect.Method.invoke(Method.java:566)\\n        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)\\n        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\\n        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\\n        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)\\n        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)\\n        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\\n        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\\n        at java.base/java.lang.Thread.run(Thread.java:834)
Dec 05 14:03:57 node1-1 java[24252]: 2020-12-05T08:03:57.542-0600 INFO scheduling-4 c.h.m.i.p.r.RecordFileParser Finished parsing 0 transactions from record file /home/oleg/hedera-mirror-node/./data/recordstreams/valid/2020-12-03T21_13_36.051261Z.rcd in 0ms (0/s). Success: false
Dec 05 14:03:57 node1-1 java[24252]: 2020-12-05T08:03:57.542-0600 ERROR scheduling-4 c.h.m.i.p.r.RecordFilePoller Error parsing file 2020-12-03T21_13_36.051261Z.rcd com.hedera.mirror.importer.exception.MissingFileException: File not found in the database: 2020-12-03T21_13_36.051261Z.rcd\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.lambda$onStart$0(SqlEntityListener.java:152)\\n        at java.base/java.util.Optional.orElseThrow(Optional.java:408)\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onStart(SqlEntityListener.java:152)\\n        at com.hedera.mirror.importer.parser.record.entity.sql.SqlEntityListener.onStart(SqlEntityListener.java:69)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:147)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser$$FastClassBySpringCGLIB$$8b9310db.invoke(<generated>)\\n        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)\\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\\n        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)\\n        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)\\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\\n        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)\\n        at com.hedera.mirror.importer.parser.record.RecordFileParser$$EnhancerBySpringCGLIB$$64e13bee.parse(<generated>)\\n        at com.hedera.mirror.importer.parser.record.RecordFilePoller.loadRecordFiles(RecordFilePoller.java:95)\\n        at com.hedera.mirror.importer.parser.record.RecordFilePoller.poll(RecordFilePoller.java:70)\\n        at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)\\n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n        at java.base/java.lang.reflect.Method.invoke(Method.java:566)\\n        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)\\n        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\\n        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\\n        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)\\n        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)\\n        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\\n        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\\n        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by astudnev** [comment]
After removing these files and deleting data directory i get the errors:

```
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.950-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_20.107405001Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.950-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_22.195365001Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.951-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_24.179156002Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.951-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_26.147783003Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.952-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_28.011145Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.952-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_30.044466006Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.953-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_32.104757007Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.953-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_34.094144Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.954-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2020-12-05T09_01_36.130419005Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
Dec 06 09:43:43 node1-1 java[569]: 2020-12-06T03:43:43.954-0600 WARN scheduling-4 c.h.m.i.d.r.RecordFileDownloader Signature verification failed for file 2020-12-05T09_01_38.036322009Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}
```

**Comment by steven-sheehy** [comment]
@astudnev What network are you configured to use? By the looks of the latter logs it seems to be testnet. Perhaps you can provide your custom application.yaml with the keys redacted?

These logs look to be from when the error was repeating. Can you provide the logs for when the issue first started occurring? You should be able to search the logs for the earliest occurrence of `2020-12-03T21_13_36.051261Z.rcd` and copy paste from there until you start seeing `File not found in the database` repeat.

**Comment by steven-sheehy** [comment]
@astudnev We see the problem now as we experienced when upgrading one of our less used environments from a really old version. This occurs due to a change in how we persist the record files in one of the versions you upgraded. We now expect a row to exist for them in `record_file` table that should be inserted by the downloader thread. Since you had some record files downloaded and stored in your `${dataDir}/recordstreams/valid/` folder before upgrading and we only insert the entry for newly downloaded files, this error occurs. We will create a migration to correct this.
