### ISSUE TITLE
V2 REST API test failures

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#1584]
**Detailed Description**
The V2 REST API workflow periodically fails in GitHub Actions. Seems to be TimescaleDB related as the error mentions chunks. Example:

https://github.com/hashgraph/hedera-mirror-node/runs/1895324408?check_suite_focus=true

**Actual Behavior**
```
  ● DB integration test - transactions.reqToSql - no query string - 3 txn 9 xfers

    error: insert/update/delete not permitted on chunk "_hyper_15_1_chunk"

      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:424:60)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:264:16)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:116:24)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:19:38)
```

**Expected Behavior**
No test failures

**Environment:**
- Version: master

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by xin-hedera** [comment]
this now happens in importer test as well:

https://github.com/hashgraph/hedera-mirror-node/pull/1608/checks?check_run_id=1956453874

```
2021-02-22T22:17:31.5190164Z [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.14 s - in com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordItemListenerTest
2021-02-22T22:17:31.5206493Z [INFO] Running com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest
2021-02-22T22:18:29.1452596Z 2021-02-22T16:18:20.946-0600 ERROR main c.p.t.p.EmbeddedPubsubBootstrapConfiguration google/cloud-sdk:290.0.1 startup time is 49 seconds 
2021-02-22T22:18:29.1454212Z 
2021-02-22T22:18:29.1454728Z            ,:if0@@@@@@@0f1;,.
2021-02-22T22:18:29.1455331Z        :L@@@@@@@@@@@@@@@@@@@@@C;
2021-02-22T22:18:29.1455890Z      ,L@@@@@@@@@@@@@@@@@@@@@@@@@C:
2021-02-22T22:18:29.1456393Z     ;0@@@@@@@@@@@@@@@@@@@@@@@@@@@81
2021-02-22T22:18:29.1457092Z    :0@@@@@@@1 10@@@@@@@@1 1@@@@@@@8i             1@L        ;@L.                      @@t
2021-02-22T22:18:29.1457775Z   ,L@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@0:            1@L        ;@L.                      @@t
2021-02-22T22:18:29.1458426Z   ;@@@@@@@@@1  _________  1@@@@@@@@@1            1@L        ;@L.   i@@@@@;     :@@@@@;@@t   .t@@@@f,   i@@@@@@t. .f@@@@@@@i  TM
2021-02-22T22:18:29.1460289Z  .1@@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@@C.           1@0000000000@L. :@@;  :f@G,  C@@:'':0@@t  1@@:  :@@f. t@@@::::' t8@1'':L@@t
2021-02-22T22:18:29.1461119Z  .1@@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@@C.           1@@@@@@@@@@@@L. C@@@@@@@@@t i@@.     @@t ;8@@@@@@@@81 t@C      ;0@.     L@t
2021-02-22T22:18:29.1461818Z   ;@@@@@@@@@1  _________  1@@@@@@@@@1            1@L        ;@L. C@:         i@@.     @@t ;@@:         t@C      ;0@.    .L@t
2021-02-22T22:18:29.1462635Z   ,L@@@@@@@@1 1@@@@@@@@@1 1@@@@@@@@0:            1@L        ;@L. ;@@@i:;t@@;  L@@1::i@@@t  1@@t;,;f8C: t@C       t@@t;:iC@@t
2021-02-22T22:18:29.1463387Z    :G@@@@@@@1 1@@@@@@@@@1 1@@@@@@@8;             ;@1        :@i    ;@@@@@i.    :t@@@@;tL;   ,i@@@@t;.  i@1        ,1@@@L;1@i
2021-02-22T22:18:29.1463983Z     :G@@@@@@@@@@@@@@@@@@@@@@@@@@@8i
2021-02-22T22:18:29.1464594Z      .f8@@@@@@@@@@@@@@@@@@@@@@@@L,
2021-02-22T22:18:29.1465337Z         ,L8@@@@@@@@@@@@@@@@@@0C:                                          Mirror Importer 
2021-02-22T22:18:29.1466152Z            ':if0@@@@@@@0fi:'
2021-02-22T22:18:29.1466467Z 
2021-02-22T22:18:29.1467709Z 2021-02-22T16:18:25.265-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest The following profiles are active: pubsub 
2021-02-22T22:18:29.1470085Z 2021-02-22T16:18:26.21***-0600 INFO main c.h.m.i.c.CredentialsProviderConfiguration Setting up S*** async client using AWS Default Credentials Provider 
2021-02-22T22:18:29.1471986Z 2021-02-22T16:18:26.27***-0600 INFO main o.f.c.i.c.DbMigrate Current version of schema "public": << Empty Schema >> 
2021-02-22T22:18:29.1510309Z 2021-02-22T16:18:26.278-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.6 - Missing Entities 
2021-02-22T22:18:29.1512617Z 2021-02-22T16:18:26.278-0600 INFO main c.h.m.i.m.V1_11_6__Missing_Entities Migration 1.11.6 will be skipped as it does not fall between the baseline: 1.999.999 and target: 2.999.999 range 
2021-02-22T22:18:29.1598508Z 2021-02-22T16:18:26.***0***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.0 - time scale init 
2021-02-22T22:18:29.1600517Z 2021-02-22T16:18:26.***5***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.1 - hyper tables 
2021-02-22T22:18:29.1602030Z 2021-02-22T16:18:26.***89-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.2 - time scale index init 
2021-02-22T22:18:29.1603545Z 2021-02-22T16:18:26.4***5-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.*** - time scale compression 
2021-02-22T22:18:29.1605174Z 2021-02-22T16:18:26.506-0600 INFO main o.f.c.i.c.DbMigrate Successfully applied 5 migrations to schema "public" (execution time 00:00.2***6s) 
2021-02-22T22:18:29.1610433Z 2021-02-22T16:18:26.746-0600 WARN main o.s.c.g.c.DefaultCredentialsProvider No core credentials are set. Service-specific credentials (e.g., spring.cloud.gcp.pubsub.credentials.*) should be used if your app uses services that require credentials. java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2021-02-22T22:18:29.1615992Z 	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:1***4)
2021-02-22T22:18:29.1619207Z 2021-02-22T16:18:27.2***4-0600 INFO main c.h.m.i.c.MirrorImporterConfiguration Configured to download from S*** in region us-east-1 with bucket name 'test' 
2021-02-22T22:18:29.1621386Z 2021-02-22T16:18:29.1***4-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest Started PubSubRecordParserTest in 57.594 seconds (JVM running for 114.057) 
2021-02-22T22:18:31.0345136Z 2021-02-22T16:18:29.217-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest Executing: testPubSubExporter() 
2021-02-22T22:18:31.0347874Z 2021-02-22T16:18:***0.08***-0600 INFO main c.h.m.i.r.r.CompositeRecordFileReader Loading record format version 2 from record file: 2019-08-***0T18_10_00.419072Z.rcd 
2021-02-22T22:18:31.0351067Z 2021-02-22T16:18:***0.116-0600 INFO main c.h.m.i.c.MirrorDateRangePropertiesProcessor RECORD: parser will parse items in the range [1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z] 
2021-02-22T22:18:31.0353673Z 2021-02-22T16:18:***0.64***-0600 INFO main c.h.m.i.p.r.RecordFileParser Finished parsing 19 transactions from record file 2019-08-***0T18_10_00.419072Z.rcd in 5***.8 ms. Success: true 
2021-02-22T22:18:31.0355835Z 2021-02-22T16:18:***0.649-0600 INFO main c.h.m.i.r.r.CompositeRecordFileReader Loading record format version 2 from record file: 2019-08-***0T18_10_05.249678Z.rcd 
2021-02-22T22:18:31.0358957Z 2021-02-22T16:18:***0.891-0600 WARN main c.z.h.p.ProxyConnection test_db - Connection org.postgresql.jdbc.PgConnection@***b4e9c4f marked as broken because of SQLSTATE(0A000), ErrorCode(0) org.postgresql.util.PSQLException: ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-22T22:18:31.0361127Z   Hint: Make sure the chunk is not compressed.
2021-02-22T22:18:31.0412726Z 2021-02-22T16:18:***0.900-0600 WARN main o.h.e.j.s.SqlExceptionHelper SQL Error: 0, SQLState: 0A000 
2021-02-22T22:18:31.0573234Z 2021-02-22T16:18:***0.900-0600 ERROR main o.h.e.j.s.SqlExceptionHelper ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-22T22:18:31.0574318Z   Hint: Make sure the chunk is not compressed. 
2021-02-22T22:18:31.0577741Z 2021-02-22T16:18:***0.912-0600 ERROR main c.h.m.i.p.r.RecordFileParser Error parsing file 2019-08-***0T18_10_05.249678Z.rcd org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
2021-02-22T22:18:31.0582626Z 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:***5***)
2021-02-22T22:18:31.0586440Z 2021-02-22T16:18:***0.919-0600 INFO main c.h.m.i.p.r.RecordFileParser Finished parsing 15 transactions from record file 2019-08-***0T18_10_05.249678Z.rcd in 262.6 ms. Success: false 
2021-02-22T22:18:31.0590553Z 2021-02-22T16:18:***0.920-0600 ERROR main o.s.t.i.TransactionInterceptor Application exception overridden by rollback exception org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
2021-02-22T22:18:31.0595544Z 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:***5***)
2021-02-22T22:18:31.0647047Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 59.52*** s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest
2021-02-22T22:18:31.0662756Z [ERROR] com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter  Time elapsed: 1.868 s  <<< ERROR!
2021-02-22T22:18:31.0714938Z org.springframework.transaction.TransactionSystemException: Could not roll back JPA transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
2021-02-22T22:18:31.0729905Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:65)
2021-02-22T22:18:31.0742679Z Caused by: org.hibernate.TransactionException: Unable to rollback against JDBC Connection
2021-02-22T22:18:31.0754521Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:65)
2021-02-22T22:18:31.0761244Z Caused by: java.sql.SQLException: Connection is closed
2021-02-22T22:18:31.0771025Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:65)
```

**Comment by xin-hedera** [comment]
another similar failure in importer test:

```
2021-02-24T15:05:38.7808930Z 2021-02-24T09:05:***5.054-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest The following profiles are active: pubsub 
2021-02-24T15:05:38.7811222Z 2021-02-24T09:05:***5.9***9-0600 INFO main c.h.m.i.c.CredentialsProviderConfiguration Setting up S*** async client using AWS Default Credentials Provider 
2021-02-24T15:05:38.7813109Z 2021-02-24T09:05:***6.004-0600 INFO main o.f.c.i.c.DbMigrate Current version of schema "public": << Empty Schema >> 
2021-02-24T15:05:38.7814623Z 2021-02-24T09:05:***6.006-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 1.11.6 - Missing Entities 
2021-02-24T15:05:38.7816394Z 2021-02-24T09:05:***6.006-0600 INFO main c.h.m.i.m.V1_11_6__Missing_Entities Migration 1.11.6 will be skipped as it does not fall between the baseline: 1.999.999 and target: 2.999.999 range 
2021-02-24T15:05:38.7818051Z 2021-02-24T09:05:***6.02***-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.0 - time scale init 
2021-02-24T15:05:38.7819552Z 2021-02-24T09:05:***6.064-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.1 - hyper tables 
2021-02-24T15:05:38.7821271Z 2021-02-24T09:05:***6.102-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.2 - time scale index init 
2021-02-24T15:05:38.7822868Z 2021-02-24T09:05:***6.157-0600 INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version 2.0.*** - time scale compression 
2021-02-24T15:05:38.7824513Z 2021-02-24T09:05:***6.224-0600 INFO main o.f.c.i.c.DbMigrate Successfully applied 5 migrations to schema "public" (execution time 00:00.221s) 
2021-02-24T15:05:38.7871524Z 2021-02-24T09:05:***6.474-0600 WARN main o.s.c.g.c.DefaultCredentialsProvider No core credentials are set. Service-specific credentials (e.g., spring.cloud.gcp.pubsub.credentials.*) should be used if your app uses services that require credentials. java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2021-02-24T15:05:38.7877572Z 	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:1***4)
2021-02-24T15:05:38.7880991Z 2021-02-24T09:05:***6.924-0600 INFO main c.h.m.i.c.MirrorImporterConfiguration Configured to download from S*** in region us-east-1 with bucket name 'test' 
2021-02-24T15:05:38.7883331Z 2021-02-24T09:05:***8.767-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest Started PubSubRecordParserTest in 58.144 seconds (JVM running for 116.129) 
2021-02-24T15:05:40.9847025Z 2021-02-24T09:05:***8.841-0600 INFO main c.h.m.i.p.r.p.PubSubRecordParserTest Executing: testPubSubExporter() 
2021-02-24T15:05:40.9849167Z 2021-02-24T09:05:***9.764-0600 INFO main c.h.m.i.r.r.CompositeRecordFileReader Loading record format version 2 from record file: 2019-08-***0T18_10_00.419072Z.rcd 
2021-02-24T15:05:40.9851332Z 2021-02-24T09:05:***9.798-0600 INFO main c.h.m.i.c.MirrorDateRangePropertiesProcessor RECORD: parser will parse items in the range [1970-01-01T00:00:00Z, 2262-04-11T2***:47:16.854775807Z] 
2021-02-24T15:05:40.9853434Z 2021-02-24T09:05:40.***14-0600 INFO main c.h.m.i.p.r.RecordFileParser Finished parsing 19 transactions from record file 2019-08-***0T18_10_00.419072Z.rcd in 52***.*** ms. Success: true 
2021-02-24T15:05:40.9855331Z 2021-02-24T09:05:40.***26-0600 INFO main c.h.m.i.r.r.CompositeRecordFileReader Loading record format version 2 from record file: 2019-08-***0T18_10_05.249678Z.rcd 
2021-02-24T15:05:40.9857235Z 2021-02-24T09:05:40.605-0600 INFO main c.h.m.i.p.r.RecordFileParser Finished parsing 15 transactions from record file 2019-08-***0T18_10_05.249678Z.rcd in 276.0 ms. Success: true 
2021-02-24T15:05:40.9870316Z 2021-02-24T09:05:40.624-0600 WARN main c.z.h.p.ProxyConnection test_db - Connection org.postgresql.jdbc.PgConnection@282ad647 marked as broken because of SQLSTATE(0A000), ErrorCode(0) java.sql.BatchUpdateException: Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, name, node_account_id, prev_hash, version, consensus_end) values (NULL, 1567188605249678000, 15, 0, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', NULL, NULL, NULL, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', 1, 1614179140, 1614179140, '2019-08-***0T18_10_05.249678Z.rcd', ***, '591558e059bd1629ee***86c4e***5a6875b4c67a096718f5d225772a651042715189414df7db5588495efb2a85dc4a0ffda', 2, 1567188609705***82001) was aborted: ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:40.9876433Z   Hint: Make sure the chunk is not compressed.  Call getNextException to see other errors in the batch.
2021-02-24T15:05:40.9884463Z 2021-02-24T09:05:40.6***7-0600 ERROR main o.h.e.j.b.i.BatchingBatch HHH000***15: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, name, node_account_id, prev_hash, version, consensus_end) values (NULL, 1567188605249678000, 15, 0, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', NULL, NULL, NULL, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', 1, 1614179140, 1614179140, '2019-08-***0T18_10_05.249678Z.rcd', ***, '591558e059bd1629ee***86c4e***5a6875b4c67a096718f5d225772a651042715189414df7db5588495efb2a85dc4a0ffda', 2, 1567188609705***82001) was aborted: ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:40.9890620Z   Hint: Make sure the chunk is not compressed.  Call getNextException to see other errors in the batch.], SQL: insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, name, node_account_id, prev_hash, version, consensus_end) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2021-02-24T15:05:40.9893303Z 2021-02-24T09:05:40.6***7-0600 WARN main o.h.e.j.s.SqlExceptionHelper SQL Error: 0, SQLState: 0A000 
2021-02-24T15:05:40.9900553Z 2021-02-24T09:05:40.6***7-0600 ERROR main o.h.e.j.s.SqlExceptionHelper Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, name, node_account_id, prev_hash, version, consensus_end) values (NULL, 1567188605249678000, 15, 0, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', NULL, NULL, NULL, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', 1, 1614179140, 1614179140, '2019-08-***0T18_10_05.249678Z.rcd', ***, '591558e059bd1629ee***86c4e***5a6875b4c67a096718f5d225772a651042715189414df7db5588495efb2a85dc4a0ffda', 2, 1567188609705***82001) was aborted: ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:40.9905747Z   Hint: Make sure the chunk is not compressed.  Call getNextException to see other errors in the batch. 
2021-02-24T15:05:40.9907396Z 2021-02-24T09:05:40.6***7-0600 ERROR main o.h.e.j.s.SqlExceptionHelper ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:40.9908456Z   Hint: Make sure the chunk is not compressed. 
2021-02-24T15:05:40.9910852Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.1***5 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest
2021-02-24T15:05:40.9985045Z [ERROR] com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter  Time elapsed: 1.94 s  <<< ERROR!
2021-02-24T15:05:40.9989200Z org.springframework.orm.jpa.JpaSystemException: could not execute batch; nested exception is org.hibernate.exception.GenericJDBCException: could not execute batch
2021-02-24T15:05:41.0041096Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:66)
2021-02-24T15:05:41.0044619Z Caused by: org.hibernate.exception.GenericJDBCException: could not execute batch
2021-02-24T15:05:41.0048051Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:66)
2021-02-24T15:05:41.0051053Z Caused by: java.sql.BatchUpdateException: 
2021-02-24T15:05:41.0112666Z Batch entry 0 insert into record_file (bytes, consensus_start, count, digest_algorithm, file_hash, hapi_version_major, hapi_version_minor, hapi_version_patch, hash, index, load_end, load_start, name, node_account_id, prev_hash, version, consensus_end) values (NULL, 1567188605249678000, 15, 0, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', NULL, NULL, NULL, '5ed51baeff204eb6a2a68b76bbaadcb9b6e7074676c1746b99681d075bef009e8d57699baaa6***42feec4e8***726582d***6', 1, 1614179140, 1614179140, '2019-08-***0T18_10_05.249678Z.rcd', ***, '591558e059bd1629ee***86c4e***5a6875b4c67a096718f5d225772a651042715189414df7db5588495efb2a85dc4a0ffda', 2, 1567188609705***82001) was aborted: ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:41.0117447Z   Hint: Make sure the chunk is not compressed.  Call getNextException to see other errors in the batch.
2021-02-24T15:05:41.0120832Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:66)
2021-02-24T15:05:41.0123909Z Caused by: org.postgresql.util.PSQLException: 
2021-02-24T15:05:41.0124886Z ERROR: insert/update/delete not permitted on chunk "_hyper_12_1_chunk"
2021-02-24T15:05:41.0125648Z   Hint: Make sure the chunk is not compressed.
2021-02-24T15:05:41.0128459Z 	at com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter(PubSubRecordParserTest.java:66)
2021-02-24T15:05:41.0131067Z 
```

**Comment by steven-sheehy** [comment]
I think I know the problem. From TimescaleDB docs:

> the current version of compression disallows INSERTS, UPDATES, and DELETES on compressed chunks completely (although you can manually decompress the chunk to modify it). Thus you want to compress a chunk only after it is unlikely to be modified further.

We need to remove decompression from tables that we can update like entities, tokens, etc.

**Comment by xin-hedera** [comment]
that should be the right move. Apparently the logs from importer test failures provide better description of the issue.
