### ISSUE TITLE
Slow account balance file processing at high number of accounts

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#1927]
**Detailed Description**
Performance testing of high account creation shows that it can easily slow down the importer account balance file processing to a crawl. Thread dumps and database activity shows the majority of time is spent in `COPY account_balance` queries due to the sheer number of entries in the file.

**Actual Behavior**
1. Create accounts at 2K TPS
2. Wait for at least 20M accounts to be created
3. Balance file processing exceeds 10m

**Expected Behavior**
Balance file processing to take under 10s

**Environment:**
- Java: OpenJDK 11.0.10
- OS: Ubuntu 18.04
- Version: 0.32.0

**Additional Context**
Database activity:
```
mirror_node=> select pid, now() - query_start as elapsed, query from pg_stat_activity where query not like '%pg_stat%' and state = 'active';
   pid   |     elapsed     |                                       query
---------+-----------------+------------------------------------------------------------------------------------
 3542009 | 00:01:02.853896 | COPY account_balance(balance, account_id, consensus_timestamp) FROM STDIN WITH CSV
(1 row)
```

Thread dump:
```java
"scheduling-3" #36 prio=5 os_prio=0 cpu=515357.69ms elapsed=62140.26s tid=0x00007f45528c9800 nid=0x40d3 runnable  [0x00007f44c82f2000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketOutputStream.socketWrite0(java.base@11.0.11/Native Method)
        at java.net.SocketOutputStream.socketWrite(java.base@11.0.11/SocketOutputStream.java:110)
        at java.net.SocketOutputStream.write(java.base@11.0.11/SocketOutputStream.java:150)
        at sun.security.ssl.SSLSocketOutputRecord.deliver(java.base@11.0.11/SSLSocketOutputRecord.java:319)
        - locked <0x00000005b161f3a0> (a sun.security.ssl.SSLSocketOutputRecord)
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(java.base@11.0.11/SSLSocketImpl.java:1212)
        at java.io.BufferedOutputStream.write(java.base@11.0.11/BufferedOutputStream.java:123)
        - locked <0x00000005b1622ea8> (a java.io.BufferedOutputStream)
        at org.postgresql.core.PGStream.send(PGStream.java:389)
        at org.postgresql.core.v3.QueryExecutorImpl.writeToCopy(QueryExecutorImpl.java:1048)
        - locked <0x00000005b161d868> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.core.v3.CopyInImpl.writeToCopy(CopyInImpl.java:37)
        at org.postgresql.copy.PGCopyOutputStream.writeToCopy(PGCopyOutputStream.java:135)
        at org.postgresql.copy.PGCopyOutputStream.write(PGCopyOutputStream.java:93)
        at com.fasterxml.jackson.dataformat.csv.impl.UTF8Writer.write(UTF8Writer.java:135)
        at com.fasterxml.jackson.dataformat.csv.impl.CsvEncoder._flushBuffer(CsvEncoder.java:1140)
        at com.fasterxml.jackson.dataformat.csv.impl.CsvEncoder.write(CsvEncoder.java:390)
        at com.fasterxml.jackson.dataformat.csv.CsvGenerator.writeNumber(CsvGenerator.java:811)
        at com.fasterxml.jackson.dataformat.csv.CsvGenerator.writeNumber(CsvGenerator.java:821)
        at com.fasterxml.jackson.databind.ser.std.NumberSerializers$LongSerializer.serialize(NumberSerializers.java:194)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1217)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1043)
        at com.hedera.mirror.importer.parser.PgCopy.copy(PgCopy.java:89)
        at com.hedera.mirror.importer.parser.balance.AccountBalanceFileParser.parse(AccountBalanceFileParser.java:131)
        at com.hedera.mirror.importer.parser.balance.AccountBalanceFileParser$$FastClassBySpringCGLIB$$1d75546a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:93)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:119)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at com.hedera.mirror.importer.parser.balance.AccountBalanceFileParser$$EnhancerBySpringCGLIB$$613ddd95.parse(<generated>)
```

Logs:
```
May 04 14:02:18 java[16335]: 2021-05-04T08:02:18.482-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_00_00.844472Z_Balances.pb.gz
May 04 14:12:16 java[16335]: 2021-05-04T08:12:16.762-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 9.937 min
May 04 14:12:16 java[16335]: 2021-05-04T08:12:16.905-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 143.2 ms
May 04 14:12:16 java[16335]: 2021-05-04T08:12:16.912-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_00_00.844472Z_Balances.pb.gz in 9.974 min
May 04 14:12:16 java[16335]: 2021-05-04T08:12:16.942-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_10_00.440872Z_Balances.pb.gz
May 04 14:22:22 java[16335]: 2021-05-04T08:22:22.223-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.06 min
May 04 14:22:22 java[16335]: 2021-05-04T08:22:22.360-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 137.0 ms
May 04 14:22:22 java[16335]: 2021-05-04T08:22:22.367-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_10_00.440872Z_Balances.pb.gz in 10.09 min
May 04 14:22:22 java[16335]: 2021-05-04T08:22:22.401-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_20_01.338440Z_Balances.pb.gz
May 04 14:32:32 java[16335]: 2021-05-04T08:32:32.563-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.15 min
May 04 14:32:32 java[16335]: 2021-05-04T08:32:32.701-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 138.1 ms
May 04 14:32:32 java[16335]: 2021-05-04T08:32:32.711-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_20_01.338440Z_Balances.pb.gz in 10.17 min
May 04 14:32:32 java[16335]: 2021-05-04T08:32:32.748-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_30_00.658697Z_Balances.pb.gz
May 04 14:42:35 java[16335]: 2021-05-04T08:42:35.625-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.03 min
May 04 14:42:35 java[16335]: 2021-05-04T08:42:35.787-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 161.6 ms
May 04 14:42:35 java[16335]: 2021-05-04T08:42:35.794-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_30_00.658697Z_Balances.pb.gz in 10.05 min
May 04 14:42:35 java[16335]: 2021-05-04T08:42:35.819-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_40_00.081925Z_Balances.pb.gz
May 04 14:52:45 java[16335]: 2021-05-04T08:52:45.028-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.14 min
May 04 14:52:45 java[16335]: 2021-05-04T08:52:45.142-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 114.0 ms
May 04 14:52:45 java[16335]: 2021-05-04T08:52:45.149-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_40_00.081925Z_Balances.pb.gz in 10.16 min
May 04 14:52:45 java[16335]: 2021-05-04T08:52:45.191-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T14_50_01.013669Z_Balances.pb.gz
May 04 15:02:42 java[16335]: 2021-05-04T09:02:42.357-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 9.935 min
May 04 15:02:42 java[16335]: 2021-05-04T09:02:42.499-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 141.5 ms
May 04 15:02:42 java[16335]: 2021-05-04T09:02:42.506-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T14_50_01.013669Z_Balances.pb.gz in 9.955 min
May 04 15:02:42 java[16335]: 2021-05-04T09:02:42.563-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_00_01.116962Z_Balances.pb.gz
May 04 15:12:52 java[16335]: 2021-05-04T09:12:52.984-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.15 min
May 04 15:12:53 java[16335]: 2021-05-04T09:12:53.118-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 134.0 ms
May 04 15:12:53 java[16335]: 2021-05-04T09:12:53.123-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_00_01.116962Z_Balances.pb.gz in 10.18 min
May 04 15:12:53 java[16335]: 2021-05-04T09:12:53.162-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_10_00.692071Z_Balances.pb.gz
May 04 15:22:52 java[16335]: 2021-05-04T09:22:52.438-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 9.958 min
May 04 15:22:52 java[16335]: 2021-05-04T09:22:52.551-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 112.8 ms
May 04 15:22:52 java[16335]: 2021-05-04T09:22:52.557-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_10_00.692071Z_Balances.pb.gz in 9.990 min
May 04 15:22:52 java[16335]: 2021-05-04T09:22:52.626-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_20_00.265549Z_Balances.pb.gz
May 04 15:33:18 java[16335]: 2021-05-04T09:33:18.405-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.41 min
May 04 15:33:18 java[16335]: 2021-05-04T09:33:18.541-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 135.8 ms
May 04 15:33:18 java[16335]: 2021-05-04T09:33:18.548-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_20_00.265549Z_Balances.pb.gz in 10.43 min
May 04 15:33:18 java[16335]: 2021-05-04T09:33:18.589-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_30_00.312843Z_Balances.pb.gz
May 04 15:43:32 java[16335]: 2021-05-04T09:43:32.530-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.21 min
May 04 15:43:32 java[16335]: 2021-05-04T09:43:32.667-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39257 rows to token_balance table in 136.9 ms
May 04 15:43:32 java[16335]: 2021-05-04T09:43:32.671-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_30_00.312843Z_Balances.pb.gz in 10.23 min
May 04 15:43:32 java[16335]: 2021-05-04T09:43:32.716-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_40_00.521923Z_Balances.pb.gz
May 04 15:53:38 java[16335]: 2021-05-04T09:53:38.673-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.07 min
May 04 15:53:38 java[16335]: 2021-05-04T09:53:38.816-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39259 rows to token_balance table in 142.4 ms
May 04 15:53:38 java[16335]: 2021-05-04T09:53:38.823-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_40_00.521923Z_Balances.pb.gz in 10.10 min
May 04 15:53:38 java[16335]: 2021-05-04T09:53:38.857-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T15_50_01.318875Z_Balances.pb.gz
May 04 16:04:09 java[16335]: 2021-05-04T10:04:09.766-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 20881039 rows to account_balance table in 10.49 min
May 04 16:04:11 java[16335]: 2021-05-04T10:04:11.843-0600 INFO scheduling-3 c.h.m.i.p.PgCopy Copied 39259 rows to token_balance table in 2.077 s
May 04 16:04:11 java[16335]: 2021-05-04T10:04:11.864-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Successfully processed 20881039 account balances from 2021-05-04T15_50_01.318875Z_Balances.pb.gz in 10.55 min
May 04 16:04:11 java[16335]: 2021-05-04T10:04:11.894-0600 INFO scheduling-3 c.h.m.i.p.b.AccountBalanceFileParser Starting processing account balances file 2021-05-04T16_00_01.258288Z_Balances.pb.gz
```

**Comment by steven-sheehy** [comment]
It might not necessarily be pgcopy. It could be due to too much memory usage. We should optimize balance file parser to not load all account balances into memory and instead stream them one by one. 

Recommend changing `StreamFile::getItems` from a `List` to a `Stream`. Streams are lazily evaluated and are `AutoCloseable` unlike `Iterator`. `ProtoBalanceFileReader` should construct a stream and set it on the `AccountBalanceFile.setItems()`. This stream implementation should store the compressed pb.gz bytes and iterate over it using logic similar to that inside `AllAccountBalances(CodedInputStream, ExtensionRegistryLite)` constructor. Downside is a Stream can only be consumed once.

Other alternative is `Flux<T>` if we want to start going the reactive route in importer.
