### ISSUE TITLE
Record downloader stops working with "Unable to connect to database" error

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#197]
**Detailed Description**
After about 90 minutes of running, the record downloader stops attempting to download files, with the following error being logged constantly (and it then becomes the only thing in the log from that point on):

```
2019-09-04 03:52:39,011 WARN  [main ] c.h.d.DatabaseUtilities Unable to connect to database. Will retry in 3000ms: HikariPool-1 - Connection is not available, request timed out af
```
**Actual Behavior**
Record downloader stops attempting to download files.

**Expected Behavior**
Record downloader keeps downloading files.

**Environment:**

**Additional Context**

Constant log messages like so starting at 03:52:39 and running until I bounced the service around 11:45 -

```
2019-09-04 03:52:39,011 WARN  [main ] c.h.d.DatabaseUtilities Unable to connect to database. Will retry in 3000ms: HikariPool-1 - Connection is not available, request timed out a
```

Prior to that, the first errors (and other interesting errors) seen since the app start were:

```
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]: 2019-09-04 01:33:52,457 ERROR [main ] c.h.d.RecordFileDownloader Failed downloading recordstreams/record0.0.4/2019-09-04T01_33_38.981116001Z.rcd_sig after 2.065 s
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]: com.amazonaws.SdkClientException: Unable to execute HTTP request: Too many open files
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1415) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.transfer.DownloadTaskImpl.getS3ObjectStream(DownloadTaskImpl.java:42) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.transfer.DownloadCallable.retryableDownloadS3ObjectToFile(DownloadCallable.java:281) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:135) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:53) ~[aws-java-sdk-s3-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.lang.Thread.run(Thread.java:834) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]: Caused by: java.net.SocketException: Too many open files
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.net.Socket.createImpl(Socket.java:462) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.net.Socket.getImpl(Socket.java:522) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.net.Socket.setSoTimeout(Socket.java:1141) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:120) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.conn.$Proxy22.connect(Unknown Source) ~[?:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar:4.5.5]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1238) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058) ~[aws-java-sdk-core-1.11.327.jar:?]
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]:         ... 17 more
Sep 04 01:33:52 mirrornode-publictestnet-1 java[11022]: 2019-09-04 01:33:52,459 INFO  [main ] c.h.d.RecordFileDownloader Downloaded 0 RCD signatures for node 0.0.4 in 2.115 s
S
```

```
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.u.Utility getBytes() failed - file /usr/etc/mirror-node/0.0.102 not found
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.d.RecordFileDownloader Address book file /usr/etc/mirror-node/0.0.102 empty or unavailable
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.u.Utility getBytes() failed - file /usr/etc/mirror-node/0.0.102 not found
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.s.NodeSignatureVerifier Address book file /usr/etc/mirror-node/0.0.102 is empty or unavailable
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.d.RecordFileDownloader Failed to verify record files in /var/lib/mirror-node/recordstreams/valid
```

```
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,470 ERROR [main ] c.h.d.RecordFileDownloader Failed to verify record files in /var/lib/mirror-node/recordstreams/valid
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: java.nio.file.FileSystemException: /var/lib/mirror-node/recordstreams/valid: Too many open files
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:428) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.Files.newDirectoryStream(Files.java:471) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.Files.walk(Files.java:3820) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at java.nio.file.Files.walk(Files.java:3874) ~[?:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at com.hedera.downloader.RecordFileDownloader.verifyValidRecordFiles(RecordFileDownloader.java:83) [mirror-node.jar:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at com.hedera.downloader.RecordFileDownloader.download(RecordFileDownloader.java:68) [mirror-node.jar:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]:         at com.hedera.downloader.RecordFileDownloader.main(RecordFileDownloader.java:55) [mirror-node.jar:?]
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,470 ERROR [main ] c.h.u.Utility getBytes() failed - file /usr/etc/mirror-node/0.0.102 not found
Sep
```

The file `/usr/etc/mirror-node/0.0.102` does actually exist and is valid

**Comment by steven-sheehy** [comment]
Leaking file descriptors. We need to ensure all `ResultSet`, `PreparedStatement`, `FileInputStream` and anything else implementing `AutoCloseable` are declared using try with resources.

**Comment by mike-burrage-hedera** [comment]
There were a bunch of:
```
2019-09-04 12:57:30,439 WARN  [main ] c.h.d.RecordFileDownloader Signature file count for 2019-09-04T12_57_19.160678Z.rcd_sig does not exceed 2/3 of nodes
```

messages shortly prior to the following which repeated over and over again
```
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.u.Utility getBytes() failed - file /usr/etc/mirror-node/0.0.102 not found
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.d.RecordFileDownloader Address book file /usr/etc/mirror-node/0.0.102 empty or unavailable
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.u.Utility getBytes() failed - file /usr/etc/mirror-node/0.0.102 not found
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.s.NodeSignatureVerifier Address book file /usr/etc/mirror-node/0.0.102 is empty or unavailable
Sep 04 11:37:24 mirrornode-publictestnet-1 java[15954]: 2019-09-04 11:37:24,462 ERROR [main ] c.h.d.RecordFileDownloader Failed to verify record files in /var/lib/mirror-node/recordstreams/valid
```

and then eventually the database errors.

I don't see any `ResultSet`, `PreparedStatement`, or `FileInputStream`s that would be used by the record downloader process and would leak without generating an error message at the time.

**Comment by gregscullard** [comment]
Was this shortly after deploy yesterday or several hours after ? Surely the file can't just disappear and magically re-appear again.

**Comment by steven-sheehy** [comment]
I think we're just not logging the exception properly. FileInputStream java docs state that `if the file does not exist, is a directory rather than a regular file, or for some other reason cannot be opened for reading.` So we're probably hitting that last one due to too many open files.

**Comment by mike-burrage-hedera** [comment]
That'd be my guess as well. The address book had a 1:22 timestamp, directory it's in 1:23. The error about "failed - file /usr/etc/mirror-node/0.0.102" started 1:57, DB error started happening continuously 3:52.
I was just speculating that we are getting a FileNotFound at 1:57 on due to too many open files - so the address book failed to be opened and we got a FileNotFound exception instead of something more descriptive, in this case.

**Comment by mike-burrage-hedera** [comment]
Unable to track down this problem. After setting filedescriptor limit to 65536, up from 1024 - ran for 4 hours so far with no issues. Open file descriptors bouncing between 1-3k.

Going to submit a PR to mitigate the problem by increasing the filedescriptor limit to 65536 in the systemd scripts.

**Comment by gregscullard** [comment]
Yes, this makes sense (too many files). I was just curious to know if this was in the middle of the logs or right at the beginning which could have been a first installation issue, but clearly that's not the case.

**Comment by steven-sheehy** [comment]
I think this issue was fixed by the systemd unit change to increase file descriptors. Closing and we can reopen later if need be
