### ISSUE TITLE
Fix two ignored tests in RecordFileLoggerContractTest

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#361]
Test names
- contractCreateDoNotPersist
- contractCallDoNotPersist

These were failing on unrelated changes. 
For eg: https://github.com/hashgraph/hedera-mirror-node/pull/360, https://github.com/hashgraph/hedera-mirror-node/pull/349, https://github.com/hashgraph/hedera-mirror-node/pull/348.

Logs:
```
INFO] Running com.hedera.recordFileLogger.RecordFileLoggerContractTest
[ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.18 s <<< FAILURE! - in com.hedera.recordFileLogger.RecordFileLoggerContractTest
[ERROR] contractCreateDoNotPersist  Time elapsed: 0.089 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at com.hedera.recordFileLogger.RecordFileLoggerContractTest.contractCreateDoNotPersist(RecordFileLoggerContractTest.java:208)

[ERROR] contractCallDoNotPersist  Time elapsed: 0.071 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at com.hedera.recordFileLogger.RecordFileLoggerContractTest.contractCallDoNotPersist(RecordFileLoggerContractTest.java:736)

[INFO] Running com.hedera.recordFileLogger.RecordFileLoggerCryptoTest
```

**Comment by Nana-EC** [comment]
Seems to have been fixed in #816
