### ISSUE TITLE
Long overflow when future expiration time

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#386]
**Detailed Description**
If a transaction expiration time is set far enough in the future it can overflow the long we use to store nanosecond timestamps. This will then cause the record file to halt processing and the mirror node can never proceed. Currently, system accounts (<1000) have an expiration time of `31556889864403199` which is `12/31/1000000000 @ 11:59pm (UTC)`. Thus this scenario will occur if that field is ever updated in a CryptoUpdateAccount transaction, for example.

**Actual Behavior**
Long overflow and processing halts indefinitely

**Expected Behavior**
Handle the ArithmeticException and either put null or the max value that can fit without overflowing.

**Environment:**
- Version: v0.4.0-rc2

**Additional Context**
This impacts any transaction type that has a timestamp. Other timestamps like `consensusTimestamp` and `transactionValidStart` should not be impacted as they should always be in the past in order for the transaction to make it to the mirror node.

**Comment by mike-burrage-hedera** [comment]
Investigating potential impact in mainnet/testnet

**Comment by steven-sheehy** [comment]
This occurred in development:
```console
Nov 25 20:53:45 mirrornode-dev-1 java[13261]: 2019-11-25 20:53:45,358 INFO  [scheduling-5] c.h.m.p.r.RecordFileParser Loading version 2 record file: 2019-11-16T21_50_31.218215Z.rcd
Nov 25 20:53:45 mirrornode-dev-1 java[13261]: 2019-11-25 20:53:45,360 ERROR [scheduling-5] c.h.m.u.Utility Long overflow when converting Instant to nanos timestamp : 2519-08-11T01:23:50.648045Z
Nov 25 20:53:45 mirrornode-dev-1 java[13261]: java.lang.ArithmeticException: long overflow
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.lang.Math.multiplyExact(Math.java:946) ~[?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.util.Utility.convertInstantToNanos(Utility.java:595) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.util.Utility.convertToNanos(Utility.java:606) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.Entities.updateEntity(Entities.java:142) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.Entities.updateEntity(Entities.java:211) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.RecordFileLogger.storeRecord(RecordFileLogger.java:435) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.RecordFileParser.loadRecordFile(RecordFileParser.java:176) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.RecordFileParser.loadRecordFiles(RecordFileParser.java:244) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at com.hedera.mirror.parser.record.RecordFileParser.parse(RecordFileParser.java:283) [classes!/:0.4.0]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Nov 25 20:53:45 mirrornode-dev-1 java[13261]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by steven-sheehy** [comment]
Please don't close until it is fixed in master

**Comment by apeksharma** [comment]
my bad. Why is it not in the master? Standard commit flow is to first fix in master and then backport using cherrypick.

**Comment by steven-sheehy** [comment]
Because we're creating an urgent 0.4.1 for production release on tuesday.
