### ISSUE TITLE
Migration checksum mismatch for migration version 1.65.5

### ISSUE THREAD

**Issue by dzmitrykliapkou** [hashgraph/hedera-mirror-node#4398]
### Description

We've been running Hedera Mirror node for a while using docker-compose but after a restart importer service started failing because of `Migration checksum mismatch for migration version 1.65.5` error

It's a bit unclear how we can fix this issue

### Steps to reproduce

We used the guide [here](https://docs.hedera.com/guides/mirrornet/run-your-own-beta-mirror-node/run-your-own-mirror-node-s3) to run the node 

### Additional context

```
2022-08-31T01:15:41.649-0600 INFO main c.h.m.i.MirrorImporterApplication No active profile set, falling back to 1 default profile: "default"
2022-08-31T01:15:45.726-0600 WARN main o.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.65.5
-> Applied to database : -836581828
-> Resolved locally    : -666666937
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
2022-08-31T01:15:45.784-0600 ERROR main o.s.b.SpringApplication Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation\\nMigration checksum mismatch for migration version 1.65.5\\n-> Applied to database : -836581828\\n-> Resolved locally    : -666666937\\nEither revert the changes to the migration, or run repair to update the schema history.\\nNeed more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE\\n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)\\n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)\\n    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\\n       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\\n    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\\n at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\\n     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\\n        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)\\n     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\\n       at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)\\n       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)\\n       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)\\n        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)\\n    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)\\n     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)\\n     at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\\n        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\\n        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\\n       at com.hedera.mirror.importer.MirrorImporterApplication.main(MirrorImporterApplication.java:33)\\n      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\\n     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\\n    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\\n        at java.base/java.lang.reflect.Method.invoke(Unknown Source)\\n at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\\n     at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\\n        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\\n at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\\nCaused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation\\nMigration checksum mismatch for migration version 1.65.5\\n-> Applied to database : -836581828\\n-> Resolved locally    : -666666937\\nEitherrevert the changes to the migration, or run repair to update the schema history.\\nNeed more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE\\n    at org.flywaydb.core.Flyway$1.execute(Flyway.java:130)\\n       at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)\\n        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)\\n at org.flywaydb.core.Flyway.migrate(Flyway.java:124)\\n at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)\\n   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\\n       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\\n  ... 26 more
NOTE: Picked up JDK_JAVA_OPTIONS: -XX:MaxRAMPercentage=80 -XX:TieredStopAtLevel=1
```

### Hedera network

mainnet

### Version

gcr.io/mirrornode/hedera-mirror-importer:main; gcr.io/mirrornode/hedera-mirror-rest:main; redis:6.2.6-alpine; postgres:14.2-alpine

### Operating system

Linux

**Comment by steven-sheehy** [comment]
We don't [recommend](https://github.com/hashgraph/hedera-mirror-node#running) Docker Compose for production deployments. By default, the compose file is using the `main` image which always points to the latest commit so it can occasionally break. We _strongly_ suggest if you are to use the compose file to use the version from the last generally available tag (e.g. [v0.63.0](https://github.com/hashgraph/hedera-mirror-node/blob/v0.63.0/docker-compose.yml)).

To fix the above, can blow away your database and start fresh. Or you can update the `flyway_schema_history` table to set the `checksum` from `-836581828` to `-666666937`.

**Comment by dzmitrykliapkou** [comment]
Got it, thanks
