### ISSUE TITLE
Downloader thread blocked

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4532]
### Description

The mirror node record file downloading stopped on a staging environment

### Steps to reproduce

1. Run importer
2. S3 delay with downloading a particular file

### Additional context

```bash
2022-09-20T11:25:32.104-0600 WARN pool-11-thread-12 c.h.m.i.d.r.RecordFileDownloader Failed downloading recordstreams/record0.0.9/2022-09-19T11_04_48.023869003Z.rcd_sig in 13.66 h
...
2022-09-21T11:14:56.776-0600 ERROR scheduling-4 c.h.m.i.d.r.RecordFileDownloader Error downloading files java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.awaitDone(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(Unknown Source)
	at com.hedera.mirror.importer.downloader.Downloader.downloadAndParseSigFiles(Downloader.java:263)
	at com.hedera.mirror.importer.downloader.Downloader.downloadNextBatch(Downloader.java:165)
	at com.hedera.mirror.importer.downloader.record.RecordFileDownloader.download(RecordFileDownloader.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Hedera network

other

### Version

v0.64.2

**Comment by steven-sheehy** [comment]
To fix:

* Add a `hedera.mirror.importer.downloader.timeout=30s` property
* Set that timeout on `signatureDownloadThreadPool.invokeAll()`
* Set that timeout on `PendingDownload.future.get()`

**Comment by steven-sheehy** [comment]
Opened an issue against AWS SDK for the underlying cause that terminates the future without bubbling up to the caller. https://github.com/aws/aws-sdk-java-v2/issues/3435
