### ISSUE TITLE
HCS NoSuchMethodError

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#459]
**Detailed Description**
```
importer_1  | 2019-12-20 19:39:26,668 ERROR [scheduling-2] o.s.s.s.TaskUtils$LoggingErrorHandler Unexpected error occurred in scheduled task
importer_1  | java.lang.NoSuchMethodError: 'boolean com.hederahashgraph.api.proto.java.TransactionBody.hasConsensusCreateTopic()'
importer_1  | 	at com.hedera.mirror.importer.parser.record.RecordFileLogger.storeRecord(RecordFileLogger.java:499) ~[classes/:?]
importer_1  | 	at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFile(RecordFileParser.java:176) ~[classes/:?]
importer_1  | 	at com.hedera.mirror.importer.parser.record.RecordFileParser.loadRecordFiles(RecordFileParser.java:244) ~[classes/:?]
importer_1  | 	at com.hedera.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:283) ~[classes/:?]
importer_1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
importer_1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
importer_1  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
importer_1  | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
importer_1  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
importer_1  | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
importer_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
importer_1  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
importer_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
importer_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
importer_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
importer_1  | 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Actual Behavior**
Run hcs via docker-compose

**Expected Behavior**
No stacktrace

**Environment:**
- Java: OpenJDK 11.0.4
- Node: v12
- OS: MacOS
- Version: hcs

**Additional Context**

**Comment by steven-sheehy** [comment]
Fixed by https://github.com/hashgraph/hedera-mirror-node/pull/460
