### ISSUE TITLE
S3 Port 4566 not bound failure in REST CI

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4930]
### Description

The npm tests periodically fail in CI with `Port 4566 not bound`. This occurs during stateproof tests attempting to start the localstack S3 testcontainer. Here's an example:

https://github.com/hashgraph/hedera-mirror-node/actions/runs/3500208835/jobs/5862650477

Most likely this is just due to lack of resources in CI. To address and to speed up test time, consider switching to a S3 server like https://www.npmjs.com/package/s3rver instead of a container.

### Steps to reproduce

Run Gradle in CI

### Additional context

```bash
 ● API specification tests - transactions › /{id}/stateproof › success-result-scheduled-true.json › /api/v1/transactions/0.0.1744-1614921773-715345860/stateproof?scheduled=true

    Port 4566 not bound after 60000ms for 6ec001dd3ea7768e3ef0d66fb030fdaa151f4c03b06a2af6afd14cc4f89ae543

      at node_modules/testcontainers/dist/wait-strategy.js:106:15
      at IntervalRetryStrategy.<anonymous> (node_modules/testcontainers/dist/retry-strategy.js:70:18)
      at fulfilled (node_modules/testcontainers/dist/retry-strategy.js:13:24)
```

### Hedera network

other

### Version

main

**Comment by xin-hedera** [comment]
the [s3rver](https://www.npmjs.com/package/s3rver) project is not actively maintained and there are severe vulnerability in the dependencies of the last release. we can consider switching to [S3Mock](https://github.com/adobe/S3Mock) since it's lightweight compared to locakstack, the docker image is ~50MB vs locakstack ~700MB
