### ISSUE TITLE
Monitor Kubernetes permission issue

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5162]
### Description

Similar to #5088, there is another warning indicating a lack of Kubernetes permissions. Both are regressions due to an overly broad dependency added in #5008.

### Steps to reproduce

Run the monitor in Kubernetes

### Additional context

```
2023-01-03T15:16:01.114-0600 ERROR boundedElastic-6 o.s.c.c.d.h.r.ReactiveDiscoveryClientHealthIndicator Error io.fabric8.kubernetes.client.KubernetesClientException:  Failure executing: GET at:
      https://10.8.0.1/api/v1/namespaces/previewnet/services. Message:
        Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: User "system:serviceaccount:previewnet:mirror-monitor" cannot list resource "services" in API group "" in the namespace "previewnet".
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:697)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:676)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:627)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:566)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:510)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:140)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:422)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:411)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:91)
  at org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesDiscoveryClient.getServices(KubernetesDiscoveryClient.java:307)
  at org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesDiscoveryClient.getServices(KubernetesDiscoveryClient.java:303)
  at org.springframework.cloud.kubernetes.fabric8.discovery.reactive.KubernetesReactiveDiscoveryClient.lambda$getServices$1(KubernetesReactiveDiscoveryClient.java:60)
  at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
  at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
  at io.micrometer.core.instrument.internal.TimedCallable.call(TimedCallable.java:51)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

### Hedera network

previewnet

### Version

0.70.2

### Operating system

None

**Comment by steven-sheehy** [comment]
To fix:

* Set `spring.cloud.discovery.enabled=false`. We should go ahead and set in all modules since we don't use `DiscoveryClient` to enable communication between microservices.
* Replace monitor's dependency on `org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8` with a narrower `spring-cloud-kubernetes-fabric8-autoconfig`
