### ISSUE TITLE
Monitor test accounts › Get accounts for a single account fails

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#563]
**Detailed Description**
The monitor test `accounts › Get accounts for a single account fails` consistently fails for all ports in development.

```
> hedera-mirror-rest@0.6.0-rc1 acceptancetest /opt/restapi/hedera-mirror-rest
> __acceptancetests__/acceptancetests

Running acceptance tests against 127.0.0.1:6551
 FAIL  __acceptancetests__/accounts.test.js (24.796s)
  ● Console

    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/config/application.yml
    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/application.yml

  ● Monitoring tests - accounts › Get accounts for a single account

    : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error:

      139 |     });
      140 |
    > 141 |     test('Get accounts for a single account', async () => {
          |     ^
      142 |       const url = `${moduleVars.apiPrefix}/accounts` + `/${acctestutils.fromAccNum(moduleVars.testAccounts.highest)}`;
      143 |       moduleVars.verbose && console.log(url);
      144 |       const response = await request(server).get(url);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.test (__acceptancetests__/accounts.test.js:141:5)
      at describe (__acceptancetests__/accounts.test.js:115:3)
      at Object.<anonymous> (__acceptancetests__/accounts.test.js:21:31)

 PASS  __acceptancetests__/transactions.test.js
  ● Console

    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/config/application.yml
    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/application.yml
    console.log __acceptancetests__/transactions.test.js:173
      /api/v1/transactions?account.id=98&type=credit&limit=1

 PASS  __acceptancetests__/balances.test.js
  ● Console

    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/config/application.yml
    console.log config.js:53
      Loaded configuration source: /opt/restapi/hedera-mirror-rest/application.yml


Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 1 skipped, 28 passed, 30 total
Snapshots:   0 total
Time:        27.952s, estimated 28s
Ran all test suites matching /__acceptancetests__\//i.
```

**Actual Behavior**
Run the acceptance tests in development

**Expected Behavior**
Tests to not fail

**Environment:**
- OS: Ubuntu 18.04
- Version: v0.6.0-rc1

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
idx__t_cryptotransferlists__realm_and_num_and_consensus was dropped in dev, most likely by someone adhoc while testing.
after being readded the test succeeds.
