### ISSUE TITLE
The monitors node packages not included in release tarballs

### ISSUE THREAD

**Issue by beeradb** [hashgraph/hedera-mirror-node#586]
**Detailed Description**
When attempting to start the monitor packaged in https://github.com/hashgraph/hedera-mirror-node/releases/download/v0.6.0/hedera-mirror-rest-v0.6.0.tgz you will receive errors about uninstalled node packages. This is in contrast to the primary rest component which has node packages included in the release tarball.

**Actual Behavior**
```
0|4337     | Error: Cannot find module 'dotenv'
0|4337     | Require stack:
0|4337     | - /opt/restmonitor/monitoring/monitor_apis/server.js
0|4337     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
0|4337     |     at Module.Hook._require.Module.require (/home/restmonitor/.nvm/versions/node/v12.10.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|4337     |     at require (internal/modules/cjs/helpers.js:68:18)
0|4337     |     at Object.<anonymous> (/opt/restmonitor/monitoring/monitor_apis/server.js:23:1)
0|4337     |     at Module._compile (internal/modules/cjs/loader.js:936:30)
0|4337     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
0|4337     |     at Module.load (internal/modules/cjs/loader.js:790:32)
0|4337     |     at Function.Module._load (internal/modules/cjs/loader.js:703:12)
0|4337     |     at Object.<anonymous> (/home/restmonitor/.nvm/versions/node/v12.10.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
0|4337     |     at Module._compile (internal/modules/cjs/loader.js:936:30) {
0|4337     |   code: 'MODULE_NOT_FOUND',
0|4337     |   requireStack: [ '/opt/restmonitor/monitoring/monitor_apis/server.js' ]
0|4337     | }
```
**Expected Behavior**
It looks like this requirement is documented in the [package.json](https://github.com/hashgraph/hedera-mirror-node/blob/master/hedera-mirror-rest/monitoring/monitor_apis/package.json) for the component, it just needs to be built & included in the tarball.

**Comment by steven-sheehy** [comment]
Yeah, monitor is not packaged for release. There is an enhancement ticket for this: https://github.com/hashgraph/hedera-mirror-node/issues/228
