### ISSUE TITLE
NPE getting contract code

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5886]
### Description

The example in https://github.com/hashgraph/hedera-json-rpc-relay/issues/1114 instead of getting a 431 as described, receives a 503. On the server it shows a NPE:

```
  [ pod/mirror-web3-79b9dbd98c-5ztd5/web3 ] 2023-04-22T13:56:48.384-0600 ERROR reactor-http-nio-1 c.h.m.w.c.ContractController Generic error:
                                              java.lang.NullPointerException: Cannot invoke "org.apache.tuweni.bytes.Bytes.size()" because the return value of "org.hyperledger.besu.evm.account.Account.getCode()" is null
  at org.hyperledger.besu.evm.operation.ExtCodeSizeOperation.execute(ExtCodeSizeOperation.java:54)
  at com.hedera.node.app.service.evm.contracts.operations.HederaExtCodeSizeOperation.lambda$execute$2(HederaExtCodeSizeOperation.java:70)
  at com.hedera.node.app.service.evm.contracts.operations.HederaEvmOperationsUtil.addressCheckExecution(HederaEvmOperationsUtil.java:57)
  at com.hedera.node.app.service.evm.contracts.operations.HederaExtCodeSizeOperation.execute(HederaExtCodeSizeOperation.java:66)
  at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:282)
  at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161)
  at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173)
  at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:222)
  at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:165)
  at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessor.execute(MirrorEvmTxProcessor.java:87)
  at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorFacadeImpl.execute(MirrorEvmTxProcessorFacadeImpl.java:102)
  at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:74)
  at com.hedera.mirror.web3.service.ContractCallService.processCall(ContractCallService.java:61)
  at com.hedera.mirror.web3.controller.ContractController.call(ContractController.java:87)
  at jdk.internal.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145)
  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
  at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:258)
  at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:347)
  at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
  at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101)
  at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
  at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
  at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
  at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
  at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
  at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
  at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
  at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
  at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
  at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
  at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
  at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
  at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:663)
  at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:195)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:274)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:242)
  at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:40)
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)\\at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base/java.lang.Thread.run(Unknown Source)
  [ pod/mirror-web3-79b9dbd98c-5ztd5/web3 ] 2023-04-22T13:56:48.385-0600 INFO reactor-http-nio-1 c.h.m.w.c.LoggingFilter * POST https://testnet.mirrornode.hedera.com/api/v1/contracts/call in 109 ms: 500 INTERNAL_SERVER_ERROR
```

### Steps to reproduce

```
curl -X 'POST' \
  'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "block": "latest",
  "data": "0x1749e1e300000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004600000000000000000000000007155817ede50ca3e6a2ab39be73c97bc892f421300000000000000000000000000000000000000000000000000000000000ac1e8000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a4cdca175300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000002b00000000000000000000000000000000003ca60b00012c0000000000000000000000000000000000000d24000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007155817ede50ca3e6a2ab39be73c97bc892f421300000000000000000000000000000000000000000000000000000000000ac1e8000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a4cdca175300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000002b00000000000000000000000000000000003ca60b0005dc0000000000000000000000000000000000000d24000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007155817ede50ca3e6a2ab39be73c97bc892f421300000000000000000000000000000000000000000000000000000000000ac1e8000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c4cdca175300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000003ca60b00012c0000000000000000000000000000000000000e120005dc00000000000000000000000000000000003ca60b00012c0000000000000000000000000000000000000d2400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007155817ede50ca3e6a2ab39be73c97bc892f421300000000000000000000000000000000000000000000000000000000000ac1e8000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c4cdca175300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000003ca60b00012c0000000000000000000000000000000000000e120005dc00000000000000000000000000000000003ca60b0005dc0000000000000000000000000000000000000d240000000000000000000000000000000000000000000000000000000000000000000000",
  "estimate": false,
  "gas": 7000000,
  "to": "0x688220f76a11702273d8c4a9be798355f1cbf01d"
}'
```

### Hedera network

testnet

### Version

0.78.1

### Operating system

None

**Comment by steven-sheehy** [comment]
User confirmed it works with latest version
