### ISSUE TITLE
REST API crashes when database error

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#631]
**Detailed Description**
Testing disaster recovery against HA PostgreSQL in Kubernetes and discovered that the REST API crashes when the database is in the process of failing over. Express does not seem to handle async errors at all.

**Actual Behavior**
Repeatedly `curl -s "http://host:6551/api/v1/transactions?limit=1"`:
```console
events.js:293
      throw er; // Unhandled 'error' event
      ^

error: unable to read data from DB node 1
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:316:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on Pool instance at:
    at Client.idleListener (/usr/src/app/node_modules/pg-pool/index.js:59:10)
    at Client.emit (events.js:316:20)
    at connectedErrorHandler (/usr/src/app/node_modules/pg/lib/client.js:202:10)
    at Connection.connectedErrorMessageHandler (/usr/src/app/node_modules/pg/lib/client.js:209:7)
    at Connection.emit (events.js:316:20)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:316:20)
    [... lines matching original stack trace ...]
    at Socket.Readable.push (_stream_readable.js:214:10) {
  name: 'error',
  length: 105,
  severity: 'FATAL',
  code: 'XX000',
  detail: 'EOF encountered with backend',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pool_stream.c',
  line: '276',
  routine: undefined,
  client: Client {
    _events: [Object: null prototype] { error: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    connectionParameters: ConnectionParameters {
      user: 'mirror_api',
      database: 'mirror_node',
      port: 5432,
      binary: false,
      ssl: false,
      client_encoding: '',
      replication: undefined,
      isDomainSocket: false,
      application_name: undefined,
      fallback_application_name: undefined,
      statement_timeout: false,
      idle_in_transaction_session_timeout: false,
      query_timeout: false,
      connect_timeout: 0
    },
    user: 'mirror_api',
    database: 'mirror_node',
    port: 5432,
    replication: undefined,
    _Promise: [Function: Promise],
    _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
    _ending: true,
    _connecting: false,
    _connected: true,
    _connectionError: false,
    _queryable: false,
    connection: Connection {
      _events: [Object: null prototype],
      _eventsCount: 22,
      _maxListeners: undefined,
      stream: [Socket],
      _keepAlive: false,
      _keepAliveInitialDelayMillis: 0,
      lastBuffer: false,
      lastOffset: 0,
      buffer: null,
      offset: 101,
      encoding: 'utf8',
      parsedStatements: {},
      writer: [Object],
      ssl: false,
      _ending: true,
      _mode: 0,
      _emitMessage: false,
      _reader: [Object],
      [Symbol(kCapture)]: false
    },
    queryQueue: [],
    binary: false,
    processID: 8494,
    secretKey: 1454934283,
    ssl: false,
    _connectionTimeoutMillis: 0,
    release: [Function (anonymous)],
    activeQuery: null,
    readyForQuery: true,
    hasExecuted: true,
    [Symbol(kCapture)]: false
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hedera-mirror-rest@0.8.0-rc1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hedera-mirror-rest@0.8.0-rc1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Expected Behavior**
Return 503 and message database is down, retry later.

**Environment:**
- Java: 11
- Node: 13
- OS: Kubernetes
- Version: master

**Additional Context**

**Comment by steven-sheehy** [comment]
I tried to use [`@awaitjs/express`](https://thecodebarbarian.com/introducing-await-js-express-async-support-for-express-apps.html) to address the problem, but because the method chain is not async down to the db layer where the problem originates it caused other problems. To really solve this:

- Use `@awaitjs/express` with `getAsync()` and `decorateApp()`
- Remove unused `Cacher.js`
- Convert service methods to be async and return promises (if not already)
- Throw errors instead of writing to http response object. Create custom error classes for each type.
- Use a centralized error handler in `server.js` to map errors to http responses.
- Remove catches elsewhere and let them bubble up to central error handler
