### ISSUE TITLE
Running acceptance tests with ECDSA operator account fails

### ISSUE THREAD

**Issue by jascks** [hashgraph/hedera-mirror-node#6628]
### Description

Running acceptance tests using an ED25519 based operator account is successful. However, when using an ECDSA account two tests then fail.

**erc.feature**
And I call the erc contract via the mirror node REST API for token ownerOf
```
Step failed
Expected :"008b637266b412fbb693d451ce8e9ca51aec76d4"
Actual   :"0000000000000000000000000000000000003071"
<Click to see difference>

org.opentest4j.AssertionFailedError: 
expected: "008b637266b412fbb693d451ce8e9ca51aec76d4"
 but was: "0000000000000000000000000000000000003071"
	at jdk.internal.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.validateAddress(AbstractNetworkClient.java:185)
	at com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.ownerOfContractCall(ERCContractFeature.java:182)
	at ✽.I call the erc contract via the mirror node REST API for token ownerOf(file:///Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-test/src/test/resources/features/contract/erc.feature:14)
```

**precompile.feature**
And the contract call REST API should return the information for token for a fungible token
```
Step failed
Expected :"008b637266b412fbb693d451ce8e9ca51aec76d4"
Actual   :"0000000000000000000000000000000000003155"
<Click to see difference>

org.opentest4j.AssertionFailedError: 
expected: "008b637266b412fbb693d451ce8e9ca51aec76d4"
 but was: "0000000000000000000000000000000000003155"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.validateAddress(AbstractNetworkClient.java:185)
	at com.hedera.mirror.test.e2e.acceptance.steps.PrecompileContractFeature.baseFixedFeeCheck(PrecompileContractFeature.java:999)
	at com.hedera.mirror.test.e2e.acceptance.steps.PrecompileContractFeature.baseGetInformationForTokenChecks(PrecompileContractFeature.java:1018)
	at com.hedera.mirror.test.e2e.acceptance.steps.PrecompileContractFeature.getInformationForTokenOfFungibleToken(PrecompileContractFeature.java:496)
	at ✽.the contract call REST API should return the information for token for a fungible token(file:///Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-test/src/test/resources/features/contract/precompile.feature:21)
```

It looks like it comes down to this method in `AbstractNetworkClient`:

```
    public void validateAddress(final String actualAddress) {
        final var account = getSdkClient().getExpandedOperatorAccountId();

        assertThat(actualAddress)
                .isEqualTo(
                        account.getPublicKey().isECDSA()
                                ? account.getPublicKey().toEvmAddress().toString()
                                : account.getAccountId().toSolidityAddress());
    }
```

### Steps to reproduce

Run acceptance tests using an ECDSA based operator account ID and private key.

### Hedera network

previewnet

### Version

Latest main branch

### Operating system

macOS

**Comment by zhpetkov** [comment]
I tested running acceptance tests using an ECDSA-based operator account ID and private key via PREVIEWNET and these tests passed. 
![image](https://github.com/user-attachments/assets/4bfbce5d-d2eb-4b9a-a33e-6ba838e64498)
![image](https://github.com/user-attachments/assets/3d09350f-c3aa-4de6-9479-b86dce92a43c)

**Comment by jascks** [comment]
Thank you @zhpetkov! I'm also unable to repro. Closing
