### ISSUE TITLE
Crypto allowance acceptance fails in previewnet on allowance deletion

### ISSUE THREAD

**Issue by jascks** [hashgraph/hedera-mirror-node#6708]
### Description

As reported in the [mirror-node Slack channel](https://swirldslabs.slack.com/archives/C03DNJ4UD37/p1692710351551929), the recently added crypto allowance acceptance test is now failing due to the fact the mirror node REST API was recently updated to no longer return deleted crypto allowances.

The current acceptance test invokes the API to verify for the allowance (owner+spender) the `amount` and `amount_granted` fields are both zero.

### Steps to reproduce

 Run the `cryptoAllowance.feature` acceptance test targeting previewnet, and the very last step, verifying via the REST API that the allowance has been deleted fails:
```
Step failed
java.lang.AssertionError: 
Expecting actual not to be empty
	at com.hedera.mirror.test.e2e.acceptance.steps.AccountFeature.verifyMirrorAPIApprovedCryptoAllowanceResponse(AccountFeature.java:237)
	at com.hedera.mirror.test.e2e.acceptance.steps.AccountFeature.verifyCryptoAllowanceDelete(AccountFeature.java:273)
	at ✽.the mirror node REST API should confirm the crypto allowance deletion(file:///Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-test/src/test/resources/features/account/cryptoAllowance.feature:19)
```

### Hedera network

previewnet

### Version

0.87.1

### Operating system

macOS

**Comment by jascks** [comment]
Sync'd with Xin and the solution is to verify API response of 200 and an empty allowance list.
