### ISSUE TITLE
contracts/call requests with encoded data of 640,138 bytes returns a 500 response.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-mirror-node#6717]
### Description

The attached curl request shows a request that fails with a 500 response against the mirror node.  It generates the following exception in the web3 container:
```
2023-08-22T16:46:12.475-0600 ERROR reactor-http-nio-3 c.h.m.w.c.ContractController Generic error:  org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144\n	at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:99)\n	at org.springframework.core.io.buffer.LimitedDataBufferList.updateCount(LimitedDataBufferList.java:92)\n	at org.springframework.core.io.buffer.LimitedDataBufferList.add(LimitedDataBufferList.java:58)\n	at reactor.core.publisher.MonoCollect$CollectSubscriber.onNext(MonoCollect.java:103)\n	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)\n	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)\n	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)\n	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:377)\n	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)\n	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:672)\n	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n	at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:202)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n
```
[curl-example-request.curl.zip](https://github.com/hashgraph/hedera-mirror-node/files/12413757/curl-example-request.curl.zip)

### Steps to reproduce

1. The smart contracts test 'should be able to aggregate 1000 calls to processLongInput' will reproduce this if the Hedera JSON RPC Relay is set to use the mirror node: https://github.com/hashgraph/hedera-smart-contracts
2. However, the attached curl script will run the same request that is listed in step one.
[curl-example-request.curl.zip](https://github.com/hashgraph/hedera-mirror-node/files/12413793/curl-example-request.curl.zip)

### Hedera network

other

### Version

v0.86.0

### Operating system

macOS

**Comment by ebadiere** [comment]
Closing to modify the test to conform to the ContractCallRequest max data length setting:
```
@Hex(maxLength = 24576 * 2) // HAPI caps contract creates at 24KiB
private String data;
```
