### ISSUE TITLE
relay/web3: Null Pointer Exception on eth_call

### ISSUE THREAD

**Issue by kasey-alusi-vcc** [hashgraph/hedera-mirror-node#6794]
### Description

Running a mainnet hedera mirror node and json-rpc relay, the `eth_call` request below causes a null pointer exception in the web3 service.

`eth_call` request:
```
curl <RELAY_URL> -X POST    -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"to":"0x00000000000000000000000000000000001a88bc","data":"0x574f2ba3"},"0x326A6D6"]}'
```

Response from relay:
```
{"result":"0x","jsonrpc":"2.0","id":1}
```

relay logs:
```
[2023-09-03 20:19:45.534 +0000] TRACE (relay-eth/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] call({to=0x00000000000000000000000000000000001a88bc, from=undefined, value=undefined, gas=undefined, ...}, blockParam=0x326A6D6)
[2023-09-03 20:19:45.536 +0000] DEBUG (mirror-node/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] [GET] blocks?limit=1&order=desc 200 2 ms
[2023-09-03 20:19:45.537 +0000] WARN (relay-eth/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] referenced block '0x326A6D6' trails latest by 12907, max trailing count is 5. Throwable UNSUPPORTED_HISTORICAL_EXECUTION scenario.
[2023-09-03 20:19:45.537 +0000] DEBUG (relay-eth/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] Making eth_call on contract 0x00000000000000000000000000000000001a88bc with gas 400000 and call data "0x574f2ba3" from "undefined" using mirror-node.
[2023-09-03 20:19:45.548 +0000] DEBUG (mirror-node/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] [POST] contracts/call 500 status
[2023-09-03 20:19:45.548 +0000] WARN (mirror-node/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] [POST] contracts/call Error details: ( StatusCode: '500', StatusText: 'Internal Server Error', Data: '{"_status":{"messages":[{"message":"Internal Server Error","detail":"","data":""}]}}')
[2023-09-03 20:19:45.548 +0000] INFO (rpc-server/118 on 757c5c29efb7): [Request ID: b2f41989-56c3-4891-8f9f-7019eb8508d7] [POST]: eth_call 200 15 ms
```

`web3` logs:
```
2023-09-03T20:19:45.546+0000 ERROR reactor-http-epoll-15 c.h.m.w.c.ContractController Generic error:  java.lang.NullPointerException: Cannot read the array length because "data" is null
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.parseFrom(CurrentAndNextFeeSchedule.java:306)
	at com.hedera.mirror.web3.evm.pricing.RatesAndFeesLoader.loadFeeSchedules(RatesAndFeesLoader.java:77)
	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:421)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.hedera.mirror.web3.evm.pricing.RatesAndFeesLoader$$SpringCGLIB$$0.loadFeeSchedules(<generated>)
	at com.hedera.services.fees.calculation.BasicFcfsUsagePrices.defaultPricesGiven(BasicFcfsUsagePrices.java:86)
	at com.hedera.services.contracts.execution.LivePricesSource.currentFeeInTinycents(LivePricesSource.java:78)
	at com.hedera.services.contracts.execution.LivePricesSource.currentPrice(LivePricesSource.java:57)
	at com.hedera.services.contracts.execution.LivePricesSource.currentGasPrice(LivePricesSource.java:48)
	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.gasPriceTinyBarsGiven(HederaEvmTxProcessor.java:210)
	at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessor.execute(MirrorEvmTxProcessor.java:76)
	at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorFacadeImpl.execute(MirrorEvmTxProcessorFacadeImpl.java:140)
	at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:108)
	at com.hedera.mirror.web3.service.ContractCallService.processCall(ContractCallService.java:62)
	at com.hedera.mirror.web3.controller.ContractController.call(ContractController.java:78)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431)
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:682)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:202)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:536)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

2023-09-03T20:19:45.547+0000 INFO reactor-http-epoll-15 c.h.m.w.c.LoggingFilter /172.18.0.13 POST http://web3:8545/api/v1/contracts/call in 9 ms: 500 INTERNAL_SERVER_ERROR
```

Expectation:
* no internal server error/NPE from web3 service
* this eth_call response should be non-zero

### Steps to reproduce

Run the eth_call commands above against a json-rpc relay/mirror node set up.

### Additional context

Relay version: `0.29.0`

### Hedera network

mainnet

### Version

0.88.0-SNAPSHOT

### Operating system

Linux

**Comment by steven-sheehy** [comment]
Your mirror node is missing a fee schedule file and probably an exchange rate file as well.

**Comment by steven-sheehy** [comment]
Closing since it's a data problem.
