### ISSUE TITLE
REST API error: Cannot use a pool after calling end on the pool

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7279]
### Description

The REST API can see an unexpected error during shutdown `Cannot use a pool after calling end on the pool`. This can cause in-flight requests to terminate immediately instead of gracefully allow them to finish.

### Steps to reproduce

1. Send requests in a loop
2. Liveness probes fail and pod begins shutdown
3. In flight requests fail with the given error

### Additional context

```
2023-11-27T19:39:35.813Z INFO 70db2c5b ::ffff:10.4.0.3 GET /api/v1/accounts?balance=false in 18 ms: 200
2023-11-27T19:39:35.814Z INFO Startup Closing connection pool
2023-11-27T19:39:35.816Z ERROR 12c897e1 ::ffff:10.4.0.3 GET /api/v1/accounts?balance=false in 1 ms: 503 Service unavailable DbError: Cannot use a pool after calling end on the pool
    at Pool.queryQuietly (file:///home/node/app/utils.js:1438:13)
    at async getAccounts (file:///home/node/app/accounts.js:339:18)
    at async wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:64:9)
2023-11-27T19:39:35.828Z INFO db6265c9 ::ffff:10.4.0.3 GET /api/v1/accounts?balance=false in 20 ms: 200
2023-11-27T19:39:35.837Z ERROR 343e3217 ::ffff:10.4.0.3 GET /api/v1/accounts?balance=false in 1 ms: 503 Service unavailable DbError: Cannot use a pool after calling end on the pool
```

### Hedera network

other

### Version

v0.93.0-beta1

### Operating system

None

**Comment by steven-sheehy** [comment]
Possible solution:

* Change `health.js` `beforeShutdown` to register with `onShutdown` hook instead
* Test fix to verify the error is not seen and in-flight requests terminate gracefully without a 503
