### ISSUE TITLE
NPE in Reactor Netty

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#739]
**Detailed Description**
NPE in GRPC logs in testnet:
```
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at java.lang.Thread.run(Thread.java:834) [?:?]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:157) ~[reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at reactor.netty.http.server.HttpServerOperations.<init>(HttpServerOperations.java:128) ~[reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]:         at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:301) ~[reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
May 04 09:28:33 mirrornode-testnet-failover-grpc-1 java[2916]: java.lang.NullPointerException: null
```

**Actual Behavior**

**Expected Behavior**
No NPE

**Environment:**
- Java: OpenJDK 11
- OS: Ubuntu 18.04
- Version: 0.9.1

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by steven-sheehy** [comment]
Should be fixed by [this](https://github.com/reactor/reactor-netty/commit/31273cf6fa2967042a53d7692f17dce2dd72ac91) commit which is available in v0.9.5. Recommend upgrading Spring Boot to 2.2.6 to pull in fixed dependency.
