### ISSUE TITLE
Improve REST api SQL query logging

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#7435]
### Problem

The convention in the javascript rest api module about SQL query and params logging is a log statement at trace level is put before the SQL is executed. It provides info for debugging often times.

However it's cumbersome to remember and implement the convention,  so it's common for some queries such trace level logging is just missing.

### Solution

To make it maintenance free, we can move the trace level logging to utils.js `Pool.prototype.queryQuietly`, we can also create an `Error` object to to find the function which calls `queryQuietly`

**Comment by jascks** [comment]
I have a follow up question, @xin-hedera. I can see in `mockPool.query()` where `new Error().stack` is utilized to determine the name of the file from which the function is called so the mocking can be done correctly (transactions, balances, accounts etc.).

So, leveraging that, In `transactions.js`, we have:

```
const getTransactions = async (req, res) => {
  // Validate query parameters first
  utils.validateReq(req, acceptedTransactionParameters);

  const query = reqToSql(req);
  if (logger.isTraceEnabled()) {
    logger.trace(`getTransactions query: ${query.query} ${utils.JSONStringify(query.params)}`);
  }

  // Execute query
  const {rows, sqlQuery} = await pool.queryQuietly(query.query, query.params);
...
};
```
Note that `transactions.getTransactions` is routed to directly by `server.js`. Also note line 631 is where `pool.queryQuietly()` is invoked.

In `utils.js`, my modified `Pool.prototype.queryQuietly` defines a `new Error() so I can take a look at it in the debugger. Looking at the stack trace:
```
Error: 
    at BoundPool.Pool.queryQuietly (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/utils.js:1442:23)
    at queryQuietly (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/transactions.js:631:39)
    at wrappedMiddleware (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/node_modules/@awaitjs/express/index.js:62:26)
...
```
It looks like right after `at` is the name of the function called, not the name of the caller. But, `getTransactions` is just a variable that references the function and is not the name of the function itself. That happens to be the same stack trace IDEA displays in the debugger window.

I see that `Function.prototype.caller` has been deprecated, so I guess this stack trace is all we have to work with? If so, then it looks like the most interesting bit of information is `transactions:631` to be logged along with the SQL query and the parameters.

Not all callers reside at the root of `hedera-mirror-rest`, however. There is `controllers/ContractController`, `service/nftService`, `__tests__/integration/integrationDbOps` etc., so rather than just using the base file name, probably all path components after `hedera-mirror-rest/` are relevant along with the line number.

Does this make sense?

**Comment by jascks** [comment]
While removing all of the log statements around the code, near the bottom of my list is `baseService.js` which defines:
```
  async getRows(query, params, functionName = '') {
    if (logger.isTraceEnabled()) {
      logger.trace(`${functionName} query: ${query}, params: ${params}`);
    }
    const {rows} = await pool.queryQuietly(query, params);
    if (logger.isTraceEnabled()) {
      logger.trace(`${functionName} ${rows.length} entries`);
    }
    return rows;
  }
```
This function is called from numerous places. As it is, all will log "baseService:72 query: ...", which is much less helpful. That second logging statement with the results count will remain, of course, but the first one will be removed.

A solution may be to change `Pool.prototype.queryQuietly() to support an optional string parameter:

1. If that is defined, then use it, else examine the stack and come up with a caller location. This would retain "getTokens query: ...", "getEthTransactionByTimestampAndPayerId query: ...". But this would be mixed in with other `file:line` output where this parameter is not provided.
2. Instead always report the caller location and also add the optional parameter value. So you would see output such as "baseService:72 getTokens query: ...", "baseService:72 getEthTransactionByTimestampAndPayerId query: ..." and so forth.

While chattier, (2) would define a standard look whether or not the parameter value is defined. Problem is, though, it would be easy to get this parameter confused with the existing `preQueryHint` parameter. I don't know of a way in JS to get around parameter position. So with:

```
Pool.prototype.queryQuietly = async function (query, params = [], preQueryHint = undefined, functionName) {
   ...
}
```
To provide the function name in this case, the caller needs to use:
```
queryQuietly("sql", ["a", "b"], '', 'getTokens');
queryQuietly("sql", ["a", "b"], undefined, 'getTokens');
```
Unlike Kotlin, say, we cannot do:
```
queryQuietly("sql", ["a", "b"], functionName='getTokens');
```
One final option is to instead look lower down the stack. But where would that end? For example:
```
BoundPool.Pool.queryQuietly (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/utils.js:1445:24)
    at ContractService.queryQuietly [as getRows] (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/service/baseService.js:72:31)
    at ContractService.getRows [as getContractIdByEvmAddress] (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/service/contractService.js:511:30)
    at ContractService.getContractIdByEvmAddress [as computeContractIdFromString] (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/service/contractService.js:532:19)
    at computeContractIdFromString (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/controllers/contractController.js:108:55)
    at extractSqlFromContractFilters (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/controllers/contractController.js:717:67)
    at wrappedMiddleware (/Users/user/Development/mirrornode/repos/hedera-mirror-node/hedera-mirror-rest/node_modules/@awaitjs/express/index.js:62:26)
...
```
The direct invocation is "/baseService.js:72" as we know. The first non-library code (`node_modules`) is "controllers/contractController.js:717", and there are several in between. "service/contractService.js:511" is probably the one we'd want.

Looking for guidance on how to proceed.  For now I'll do none of this and we'll just see multiple "baseService:72 query: ...".

**Comment by xin-hedera** [comment]
for the first question, this is what I get from the error stack:

```
2024-01-16T09:57:44.566-06:00 INFO 98a1684d stack - Error
    at Pool.queryQuietly (file:///Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/utils.js:1440:19)
    at getTransactions (file:///Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/transactions.js:631:39)
    at wrappedMiddleware (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/@awaitjs/express/index.js:62:26)
    at Layer.handle [as handle_request] (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/layer.js:95:5)
    at /Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/xinli/work/hedera-mirror-node/hedera-mirror-rest/node_modules/express/lib/router/index.js:280:10)
```

Not sure why yours is different and most importantly, missing the line for the function `getTransactions`

For the second question, can just filter all the lines with stacks from `baseService.js`
