### ISSUE TITLE
Getting some `500` error status on some `contracts/call` requests

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-mirror-node#7564]
### Description

Thanks to metrics and alerts in place on the relay and HashIO, we realized that are getting some `500` errors from the mirror node for some `contracts/call` requests.

Very low percentages relative to volume, but once in a while it goes off the alert on `previewnet` due to the low volume overall of that network.

### Steps to reproduce

Run the following curl command:
```bash
curl --location 'https://previewnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "data": "0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000",
    "gas": "400000",
    "to": "0x0000000000000000000000000000000000002f03"
}'
```

### Additional context

**Response:**

500 Status
```
{
    "_status": {
        "messages": [
            {
                "message": "Internal Server Error",
                "detail": "",
                "data": ""
            }
        ]
    }
}
```
### Hedera network

mainnet, testnet, previewnet

### Version

v0.96.0

### Operating system

None

**Comment by steven-sheehy** [comment]
Not enough info. We would need a specific URL, payload, timestamp, and environment for when you saw this issue to research. You have one example above with URL, payload, and environment but no timestamp. Also, if you have metrics for how often you see this occur.

**Comment by AlfredoG87** [comment]
I did not include `timestamp` since by running the request (script) above is replicable and timestamp could be anytime is run, I just ran it now with same results. `timestamp` = `Fri, 19 Jan 2024 02:22:29 GMT`

It happens quite often:

Here are some instances by environment:

[Previewnet](https://cloudlogging.app.goo.gl/HYQoaPiGxAK26ZFv7)  28 cases in the last 2 days
[Testnet](https://cloudlogging.app.goo.gl/1CEjPfVoWSEKdTWG7) 420 cases in the last 2 days
[Mainnet](https://cloudlogging.app.goo.gl/c6wfhU9CcQ68DvJQ6) 1200 cases in the last 2 days

In terms of percentage of requests for the last 2 days

mainnet --> 0.32%
previewnet --> 2.6%
testnet --> .08%

**Comment by AlfredoG87** [comment]
> @AlfredoG87 Do you know which operation on the fungible token [this call ](https://github.com/hashgraph/hedera-mirror-node/issues/7564#:~:text=0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000) is trying to invoke because I do not find the selector for it?

@kselveliev I do not to be honest I pick it up from the logs after seeing the metrics. so not familiar with the intention of the request.

Maybe the failure is due to lack of a valid selector?

**Comment by steven-sheehy** [comment]
This is the log for the failure in previewnet:

```
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 2024-01-19T15:33:18.811Z ERROR reactor-http-epoll-3 c.h.m.w.c.ContractController Generic error:  com.hedera.node.app.service.evm.exceptions.InvalidTransactionException: Precompile result is null
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computeUsingRedirectExecutor(HTSPrecompiledContract.java:449)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.handleReadsFromDynamicContext(HTSPrecompiledContract.java:423)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.services.store.contracts.precompile.HTSPrecompiledContract.computeCosted(HTSPrecompiledContract.java:148)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmMessageCallProcessor.executeHederaPrecompile(HederaEvmMessageCallProcessor.java:87)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmMessageCallProcessor.start(HederaEvmMessageCallProcessor.java:62)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:192)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:202)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.node.app.service.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:147)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.mirror.web3.evm.contracts.execution.MirrorEvmTxProcessorImpl.execute(MirrorEvmTxProcessorImpl.java:91)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:136)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.mirror.web3.service.ContractCallService.processCall(ContractCallService.java:89)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at com.hedera.mirror.web3.controller.ContractController.call(ContractController.java:78)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$1(InvocableHandlerMethod.java:183)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:297)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:478)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:687)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:225)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:284)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 	at java.base/java.lang.Thread.run(Unknown Source)
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 
[pod/mirror-web3-7cf7b66f6b-rpszv/web3] 2024-01-19T15:33:18.813Z  INFO reactor-http-epoll-3 c.h.m.w.c.LoggingFilter 10.0.0.3 POST https://previewnet.mirrornode.hedera.com/api/v1/contracts/call in 49 ms: 500 INTERNAL_SERVER_ERROR 
```

**Comment by steven-sheehy** [comment]
Here's the trace for another call:

```
2024-01-19T19:45:21.483Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378757, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.485Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378754, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.487Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=MSTORE, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378742, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.487Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=CALLVALUE, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378740, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.487Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=DUP1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378737, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.487Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=ISZERO, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378734, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.488Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378731, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.488Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=JUMPI, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378721, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.488Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=JUMPDEST, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378720, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.488Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=POP, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378718, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.488Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378715, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.489Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH2, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378712, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.489Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=SWAP1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378709, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.489Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=POP, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378707, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.489Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH24, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378704, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.489Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378701, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.490Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=MSTORE, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378698, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.490Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=CALLDATASIZE, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378696, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.490Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378693, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.501Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378690, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.501Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=CALLDATACOPY, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378681, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.502Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378678, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.502Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=DUP1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378675, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.502Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=CALLDATASIZE, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378673, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.502Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378670, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.503Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=ADD, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378667, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.503Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=PUSH1, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378664, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.503Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=DUP5, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378661, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.503Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=GAS, callDepth=0, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=378659, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.550Z  INFO reactor-http-epoll-2 c.h.m.w.e.c.e.t.MirrorOperationTracer type=MESSAGE_CALL operation=DELEGATECALL, callDepth=1, contract=0x2f03, sender=0x, recipient=0x2f03, remainingGas=5875, revertReason=0x, input=0x1ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000, output=0x, return=0x 
2024-01-19T19:45:21.565Z ERROR reactor-http-epoll-2 c.h.m.w.c.ContractController Generic error:  com.hedera.node.app.service.evm.exceptions.InvalidTransactionException: Precompile result is null
```
