### ISSUE TITLE
Balance opcode to system account "0.0.1" acceptance test fails

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7736]
### Description

The `balance opcode to system account "0.0.1" address would return 0` acceptance test fails on testnet (and probably mainnet) since it assumes that `0.0.1` would never have a balance but in these environments it does.

### Steps to reproduce

`./gradlew :test:acceptance --info -Dcucumber.filter.tags=@acceptance`

### Additional context

```
2024-02-12T20:22:55.690Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create selfdestruct contract 
2024-02-12T20:22:55.692Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create equivalence call contract 
2024-02-12T20:22:55.692Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.HistoricalFeature Executing step: the mirror node REST API should return status 200 for the contracts creation 
2024-02-12T20:22:55.693Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the equivalence contract bytecode is deployed 
2024-02-12T20:22:55.708Z  INFO reactor-http-epoll-2 c.h.m.t.e.a.c.MirrorNodeClient GET http://mirror-rest/api/v1/contracts/0000000000000000000000000000000000338f63: 200 OK 
2024-02-12T20:22:55.710Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the selfdestruct contract bytecode is deployed 
2024-02-12T20:22:55.721Z  INFO reactor-http-epoll-1 c.h.m.t.e.a.c.MirrorNodeClient GET http://mirror-rest/api/v1/contracts/0000000000000000000000000000000000338f4b: 200 OK 
2024-02-12T20:22:55.722Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute selfdestruct and set beneficiary to "0.0.1" address 
2024-02-12T20:22:55.755Z  INFO reactor-http-epoll-4 c.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-web3/api/v1/contracts/call: 400 BAD_REQUEST 
2024-02-12T20:22:55.757Z ERROR reactor-http-epoll-4 c.h.m.t.e.a.c.MirrorNodeClient Endpoint failed, returning: 400 Bad Request from POST http://mirror-web3/api/v1/contracts/call 
2024-02-12T20:22:55.758Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute balance opcode to system account "0.0.1" address would return 0 
2024-02-12T20:22:55.796Z  INFO reactor-http-epoll-4 c.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-web3/api/v1/contracts/call: 200 OK 
2024-02-12T20:22:55.806Z ERROR ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Scenario failure: 
I successfully create selfdestruct contract
I successfully create equivalence call contract
the mirror node REST API should return status 200 for the contracts creation
I verify the equivalence contract bytecode is deployed
I verify the selfdestruct contract bytecode is deployed
I execute selfdestruct and set beneficiary to "0.0.1" address
I execute balance opcode to system account "0.0.1" address would return 0 <- 
expected: 21000
 but was: 0
I verify extcodesize opcode against a system account "0.0.1" address returns 0
I verify extcodecopy opcode against a system account "0.0.1" address returns empty bytes
I verify extcodehash opcode against a system account "0.0.1" address returns empty bytes
 org.opentest4j.AssertionFailedError: 
expected: 21000
 but was: 0
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at com.hedera.mirror.test.e2e.acceptance.steps.EquivalenceFeature.balanceOfAddress(EquivalenceFeature.java:126)
	at ✽.I execute balance opcode to system account "0.0.1" address would return 0(classpath:features/contract/equivalence.feature:12)

2024-02-12T20:22:55.811Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodesize opcode against a system account "0.0.1" address returns 0 
2024-02-12T20:22:55.811Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodecopy opcode against a system account "0.0.1" address returns empty bytes 
2024-02-12T20:22:55.812Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodehash opcode against a system account "0.0.1" address returns empty bytes 
2024-02-12T20:22:55.846Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.ERCContractFeature Executing step: I successfully create an erc contract from contract bytes with balance 0 
2024-02-12T20:22:55.847Z  INFO ForkJoinPool-1-worker-3 c.h.m.t.e.a.s.ERCContractFeature Executing step: I create a new token with freeze status 2 and kyc status 1 
```

### Hedera network

testnet

### Version

v0.98.0

### Operating system

None

**Comment by steven-sheehy** [comment]
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/issues/7741
