### ISSUE TITLE
selfdestruct with `0.0.999` beneficiary acceptance test failure

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7952]
### Description

The `I execute selfdestruct and set beneficiary to "0.0.999" address` equivalence acceptance test fails on previewnet

### Steps to reproduce

Run the below command against previewnet:

`./gradlew :test:acceptance --info -Dcucumber.filter.tags=@equivalence`

### Additional context

```
    2024-03-21T23:43:15.652Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create selfdestruct contract 
    2024-03-21T23:43:16.746Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.FileClient Created new file 0.0.1772 with 0 B via Mirror Node acceptance test: 2024-03-21T23:43:15.676687Z Create file 
    2024-03-21T23:43:18.818Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.FileClient Appended 418 B to file 0.0.1772 via 0.0.1771@1711064586.754000000 
    2024-03-21T23:43:20.958Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.ContractClient Created new contract 0.0.1773 with memo 'Mirror Node acceptance test: 2024-03-21T23:43:18.824935Z Create contract' via 0.0.1771@1711064588.825000000 
    2024-03-21T23:43:21.145Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create equivalence call contract 
    2024-03-21T23:43:23.362Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.FileClient Created new file 0.0.1774 with 0 B via Mirror Node acceptance test: 2024-03-21T23:43:21.147371Z Create file 
    2024-03-21T23:43:27.486Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.FileClient Appended 5200 B to file 0.0.1774 via 0.0.1771@1711064593.363000000 
    2024-03-21T23:43:29.543Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.ContractClient Created new contract 0.0.1775 with memo 'Mirror Node acceptance test: 2024-03-21T23:43:27.488624Z Create contract' via 0.0.1771@1711064597.488000000 
    2024-03-21T23:43:29.656Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.HistoricalFeature Executing step: the mirror node REST API should return status 200 for the contracts creation 
    2024-03-21T23:43:29.685Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the equivalence contract bytecode is deployed 
    2024-03-21T23:43:34.532Z  INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient GET https://previewnet.mirrornode.hedera.com/api/v1/contracts/00000000000000000000000000000000000006ef: 200 OK 
    2024-03-21T23:43:34.612Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the selfdestruct contract bytecode is deployed 
    2024-03-21T23:43:34.668Z  INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient GET https://previewnet.mirrornode.hedera.com/api/v1/contracts/00000000000000000000000000000000000006ed: 200 OK 
    2024-03-21T23:43:34.670Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute selfdestruct and set beneficiary to "0.0.999" address 
    2024-03-21T23:43:34.686Z  WARN ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature contract: 0.0.1773, Data: 016a373800000000000000000000000000000000000000000000000000000000000003e7 
    2024-03-21T23:43:34.765Z  INFO reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient POST https://previewnet.mirrornode.hedera.com/api/v1/contracts/call: 400 BAD_REQUEST 
    2024-03-21T23:43:34.768Z ERROR reactor-http-nio-2 c.h.m.t.e.a.c.MirrorNodeClient Endpoint failed, returning: 400 Bad Request from POST https://previewnet.mirrornode.hedera.com/api/v1/contracts/call 
    2024-03-21T23:43:34.774Z ERROR ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Scenario failure: 
    I successfully create selfdestruct contract
    I successfully create equivalence call contract
    the mirror node REST API should return status 200 for the contracts creation
    I verify the equivalence contract bytecode is deployed
    I verify the selfdestruct contract bytecode is deployed
    I execute selfdestruct and set beneficiary to "0.0.999" address <- 
    Expecting value to be true but was false
    I execute balance opcode to system account "0.0.999" address would return 0
    I verify extcodesize opcode against a system account "0.0.999" address returns 0
    I verify extcodecopy opcode against a system account "0.0.999" address returns empty bytes
    I verify extcodehash opcode against a system account "0.0.999" address returns empty bytes
     org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at com.hedera.mirror.test.e2e.acceptance.steps.EquivalenceFeature.selfDestructAndSetBeneficiary(EquivalenceFeature.java:120)
        at ✽.I execute selfdestruct and set beneficiary to "0.0.999" address(classpath:features/contract/equivalence.feature:11)

    2024-03-21T23:43:34.776Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute balance opcode to system account "0.0.999" address would return 0 
    2024-03-21T23:43:34.776Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodesize opcode against a system account "0.0.999" address returns 0 
    2024-03-21T23:43:34.777Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodecopy opcode against a system account "0.0.999" address returns empty bytes 
    2024-03-21T23:43:34.777Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodehash opcode against a system account "0.0.999" address returns empty bytes 

AcceptanceTest > Cucumber > in-equivalence tests > Validate in-equivalence system accounts for balance, extcodesize, extcodecopy, extcodehash > Examples > com.hedera.mirror.test.e2e.acceptance.AcceptanceTest.Example #1.1 FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at java.base@21.0.1/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//com.hedera.mirror.test.e2e.acceptance.steps.EquivalenceFeature.selfDestructAndSetBeneficiary(EquivalenceFeature.java:120)
        at ✽.I execute selfdestruct and set beneficiary to "0.0.999" address(classpath:features/contract/equivalence.feature:11)
```

### Hedera network

previewnet

### Version

v0.101.0-rc3

### Operating system

None

**Comment by steven-sheehy** [comment]
Previewnet is missing account 0.0.999, which should be auto created by consensus nodes
