### ISSUE TITLE
Balance opcode for "0.0.999" acceptance test fails

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#8019]
### Description

The `balance opcode to system account "0.0.999" address would return 0` fails against mainnet returns a non-zero balance.

### Steps to reproduce

1. Configure acceptance test to point at mainnet
2. `./gradlew :test:acceptance --info -Dcucumber.filter.tags=@equivalence`

### Additional context

```

AcceptanceTest > Cucumber STANDARD_OUT
    2024-04-03T21:29:04.347Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute balance opcode to system account "0.0.999" address would return 0 
    2024-04-03T21:29:04.389Z  INFO ForkJoinPool-1-worker-6 c.h.m.t.e.a.c.MirrorNodeClient Calling contract: class ContractCallRequest {
        block: latest
        data: f8b2cb4f00000000000000000000000000000000000000000000000000000000000003e7
        estimate: false
        from: 0000000000000000000000000000000000506aed
        gas: 15000000
        gasPrice: 100000000
        to: 0000000000000000000000000000000000506ac6
        value: 0
    } 
    2024-04-03T21:29:04.454Z  INFO reactor-http-nio-3 c.h.m.t.e.a.c.MirrorNodeClient POST https://mainnet.mirrornode.hedera.com/api/v1/contracts/call: 200 OK 
    2024-04-03T21:29:04.497Z ERROR ForkJoinPool-1-worker-6 c.h.m.t.e.a.s.EquivalenceFeature Scenario failure: 
    I execute balance opcode to system account "0.0.999" address would return 0 <- 
    expected: 899379576524
     but was: 0
     org.opentest4j.AssertionFailedError: 
    expected: 899379576524
     but was: 0
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at com.hedera.mirror.test.e2e.acceptance.steps.EquivalenceFeature.balanceOfAddress(EquivalenceFeature.java:126)
        at ✽.I execute balance opcode to system account "0.0.999" address would return 0(classpath:features/contract/equivalence.feature:12)


AcceptanceTest > Cucumber > in-equivalence tests > Validate in-equivalence system accounts for balance, extcodesize, extcodecopy, extcodehash > Examples > com.hedera.mirror.test.e2e.acceptance.AcceptanceTest.Example #1.1 FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 899379576524
     but was: 0
        at java.base@21.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//com.hedera.mirror.test.e2e.acceptance.steps.EquivalenceFeature.balanceOfAddress(EquivalenceFeature.java:126)
        at ✽.I execute balance opcode to system account "0.0.999" address would return 0(classpath:features/contract/equivalence.feature:12)
```

### Hedera network

mainnet

### Version

v0.100.0

### Operating system

None

**Comment by steven-sheehy** [comment]
I believe the test case is wrong and `0.0.999` should be removed as it's not in the system account range under 0.0.750 that consensus nodes use.
