### ISSUE TITLE
NoSuchKey stacktrace in REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#8055]
### Description

Getting high log error rate alerts for `NoSuchKey` in REST API.

### Steps to reproduce

Query state proof API

### Additional context

```
2024-04-09T02:17:22.585Z ERROR c89c889a Failed to download {"Bucket":"hedera-mainnet-streams","Key":"recordstreams/record0.0.31/2024-04-09T02_17_10.008160293Z.rcd_sig","RequestPayer":"requester"} NoSuchKey: The specified key does not exist.
    at de_NoSuchKeyRes (/home/node/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4809:21)
    at de_CommandError (/home/node/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4747:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/node/app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /home/node/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /home/node/app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /home/node/app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18
    at async /home/node/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /home/node/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
    at async /home/node/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'NoSuchKey',
  Details: 'No such object: hedera-mainnet-streams/recordstreams/record0.0.31/2024-04-09T02_17_10.008160293Z.rcd_sig'
}
```

### Hedera network

mainnet

### Version

v0.101.0

### Operating system

None

**Comment by steven-sheehy** [comment]
NoSuchKey can be transient if all signatures not uploaded yet or if certain nodes are down.

Solution:

* Don't print out stacktrace for NoSuchKey
* Change to warn level
