### ISSUE TITLE
Shared poller stopped with OutOfMemoryError

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#827]
**Detailed Description**
The SharedPollingTopicListener stopped polling in testnet during a high load test.

**Actual Behavior**
1. Submit Message load 2500 TPS at 512B each for 2 hrs
2. 100 client subscriptions with startTime=now, endTime=, limit=1000000 for 1hr
3. Shared poller stops

**Expected Behavior**
Shared poller doesn't stop or recovers gracefully

**Environment:**
- Java: OpenJDK 11.0
- OS: Ubuntu 18.04
- Version: 0.11.0

**Additional Context**

```console
Jun 11 21:02:42 mirrornode-stable-testnet-primary-grpc-1 java[11123]: 2020-06-11 21:02:42,082 INFO  [grpc-executor-2783] c.h.m.g.s.TopicMessageServiceImpl [JC6IdLwK] Topic 0.0.23802 cancelled with 0 messages in 8.080 min (0/s)
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142) ~[spring-data-jpa-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154) ~[spring-data-jpa-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88) ~[spring-data-jpa-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126) ~[spring-data-jpa-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at com.sun.proxy.$Proxy159.getResultList(Unknown Source) ~[?:?]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409) ~[spring-orm-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1396) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.list(Loader.java:2624) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2629) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.doList(Loader.java:2797) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.doList(Loader.java:2815) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.doQuery(Loader.java:964) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.processResultSet(Loader.java:1028) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1179) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:160) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:330) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:55) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:304) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:308) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at org.hibernate.type.descriptor.java.ArrayMutabilityPlan.deepCopyNotNull(ArrayMutabilityPlan.java:26) ~[hibernate-core-5.4.10.Final.jar!/:5.4.10.Final]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]:         at java.lang.reflect.Array.newInstance(Array.java:78) ~[?:?]
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]: java.lang.OutOfMemoryError: Java heap space
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 java[11123]: 2020-06-11 21:02:06,985 ERROR [shared-poll-1] r.c.s.Schedulers Scheduler worker in group main failed with an uncaught exception
Jun 11 21:02:09 mirrornode-stable-testnet-primary-grpc-1 systemd-journald[241]: Suppressed 1579 messages from hedera-mirror-grpc.service
```

**Comment by steven-sheehy** [comment]
Eclipse Memory Analyzer shows the top leak suspects. Suspect 2 is due to replay cache of 50K for shared poller. Other two are due to Hibernate and JDBC caching full query for JPA Criteria based `TopicMessageRepository.findByFilter()` instead of a parameterized approach. All 3 are not unbounded leaks but definitely inefficient.

![Screen Shot 2020-06-16 at 15 54 32](https://user-images.githubusercontent.com/17552371/84827223-c1176c80-afe9-11ea-9626-c833d3b8993c.png)
