### ISSUE TITLE
Some rest api endpoints return 500 with order=ASC / order=DESC

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#8790]
### Description

Some rest api endpoints return 500 with `order=ASC` /  `order=DESC`, examples:

- `https://mainnet-public.mirrornode.hedera.com/api/v1/contracts/results/logs?order=ASC`
- `https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.1274288/nfts?limit=100&order=ASC`

Stack trace:

```
TypeError: Cannot read properties of undefined (reading 'test')
    at updateReqQuery (file:///home/node/app/utils.js:815:32)
    at getNextParamQueries (file:///home/node/app/utils.js:848:5)
    at Module.getPaginationLink (file:///home/node/app/utils.js:782:12)
    at AccountController.getPaginationLink (file:///home/node/app/controllers/baseController.js:231:18)
    at getNftsByAccountId (file:///home/node/app/controllers/accountController.js:113:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:64:9)
```

problem is the order is not normalized to lower case and `operatorPatterns` in `utils.js` can only map lower case `order` to its regex pattern. 

### Steps to reproduce

check the description

### Hedera network

other

### Version

v0.108.0

### Operating system

None

**Comment by jnels124** [comment]
Issue still occurs if param supplied multiple times
