### ISSUE TITLE
Estimate Precompile Acceptance Test Fails Every Time in Integration

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9592]
### Description

```
I call estimateGas with balanceOf function for "FUNGIBLE" and verify the estimated gas against HAPI <- Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.8666@1729110650.117000000, status=CONTRACT_REVERT_EXECUTED, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=0.0.8672, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], nodeId=0, duplicates=[], children=[]}

AcceptanceTest > Cucumber > EstimateGas Contract Base Coverage Feature > com.hedera.mirror.test.e2e.acceptance.AcceptanceTest.Validate EstimateGas with precompile FAILED
    com.hedera.mirror.test.e2e.acceptance.client.NetworkException: Transaction was unsuccessful: TransactionReceipt{transactionId=0.0.8666@1729110650.117000000, status=CONTRACT_REVERT_EXECUTED, exchangeRate=ExchangeRate{hbars=1, cents=12, expirationTime=2100-01-01T00:00:00Z, exchangeRateInCents=12.0}, accountId=null, fileId=null, contractId=0.0.8672, topicId=null, tokenId=null, topicSequenceNumber=null, topicRunningHash=null, totalSupply=0, scheduleId=null, scheduledTransactionId=null, serials=[], nodeId=0, duplicates=[], children=[]}
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.getTransactionReceipt(AbstractNetworkClient.java:164)
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:135)
        at app//com.hedera.mirror.test.e2e.acceptance.client.AbstractNetworkClient.executeTransactionAndRetrieveReceipt(AbstractNetworkClient.java:152)
        at app//com.hedera.mirror.test.e2e.acceptance.client.ContractClient.executeContract(ContractClient.java:168)
        at app//com.hedera.mirror.test.e2e.acceptance.steps.EstimatePrecompileFeature.executeContractTransaction(EstimatePrecompileFeature.java:1436)
        at app//com.hedera.mirror.test.e2e.acceptance.steps.EstimatePrecompileFeature.executeBalanceOfFunctionWithLimitedGas(EstimatePrecompileFeature.java:1456)
        at ✽.I call estimateGas with balanceOf function for "FUNGIBLE" and verify the estimated gas against HAPI(classpath:features/contract/estimatePrecompile.feature:175)
```

### Steps to reproduce

```
hedera:
  mirror:
    test:
      acceptance:
        # grpc endpoint
        mirrorNodeAddress: integration.mirrornode.hedera-ops.com:443
        network: OTHER
        rest:
          baseUrl: https://integration.mirrornode.hedera-ops.com
```

Run:
`./gradlew :test:acceptance --info -Dcucumber.filter.tags=@estimateprecompile`

### Version

v0.116.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
Do we recall why this is marked as blocked?
